BEGIN;
DROP FUNCTION IF EXISTS api.move_api_keys(UUID[], UUID);
DROP FUNCTION IF EXISTS api.delete_project(UUID);
DROP FUNCTION IF EXISTS api.update_project(UUID, TEXT, TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS api.create_project(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS api.validate_api_key_project(UUID, TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS api.ensure_default_project(TEXT);
DROP FUNCTION IF EXISTS api.default_project_id(TEXT);
DROP TRIGGER IF EXISTS prevent_project_delete ON api.projects;
DROP FUNCTION IF EXISTS api.prevent_project_delete();
DROP TABLE IF EXISTS api.projects;
DROP INDEX IF EXISTS api_keys_project_name_unique_idx;
DROP INDEX IF EXISTS api_keys_project_id_idx;
ALTER TABLE api.api_keys DROP CONSTRAINT IF EXISTS api_keys_project_id_fkey;
ALTER TABLE api.api_keys DROP COLUMN IF EXISTS project_id;
ALTER TABLE api.api_keys DROP COLUMN IF EXISTS description;
DROP TYPE IF EXISTS api.project_spec;
DROP TYPE IF EXISTS api.project_status;
COMMIT;
