// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockClusterResourceService is an autogenerated mock type for the ClusterResourceService type
type MockClusterResourceService struct {
	mock.Mock
}

type MockClusterResourceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterResourceService) EXPECT() *MockClusterResourceService_Expecter {
	return &MockClusterResourceService_Expecter{mock: &_m.Mock}
}

// CollectClusterResources provides a mock function with given fields: ctx, cluster
func (_m *MockClusterResourceService) CollectClusterResources(ctx context.Context, cluster *v1.Cluster) (*v1.ClusterResources, error) {
	ret := _m.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for CollectClusterResources")
	}

	var r0 *v1.ClusterResources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster) (*v1.ClusterResources, error)); ok {
		return rf(ctx, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster) *v1.ClusterResources); ok {
		r0 = rf(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ClusterResources)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Cluster) error); ok {
		r1 = rf(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterResourceService_CollectClusterResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectClusterResources'
type MockClusterResourceService_CollectClusterResources_Call struct {
	*mock.Call
}

// CollectClusterResources is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster *v1.Cluster
func (_e *MockClusterResourceService_Expecter) CollectClusterResources(ctx interface{}, cluster interface{}) *MockClusterResourceService_CollectClusterResources_Call {
	return &MockClusterResourceService_CollectClusterResources_Call{Call: _e.mock.On("CollectClusterResources", ctx, cluster)}
}

func (_c *MockClusterResourceService_CollectClusterResources_Call) Run(run func(ctx context.Context, cluster *v1.Cluster)) *MockClusterResourceService_CollectClusterResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Cluster))
	})
	return _c
}

func (_c *MockClusterResourceService_CollectClusterResources_Call) Return(_a0 *v1.ClusterResources, _a1 error) *MockClusterResourceService_CollectClusterResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterResourceService_CollectClusterResources_Call) RunAndReturn(run func(context.Context, *v1.Cluster) (*v1.ClusterResources, error)) *MockClusterResourceService_CollectClusterResources_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterResourceService creates a new instance of MockClusterResourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterResourceService {
	mock := &MockClusterResourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
