// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	resource "github.com/neutree-ai/neutree/internal/resource"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Cluster provides a mock function with no fields
func (_m *MockManager) Cluster() resource.ClusterResourceService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cluster")
	}

	var r0 resource.ClusterResourceService
	if rf, ok := ret.Get(0).(func() resource.ClusterResourceService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ClusterResourceService)
		}
	}

	return r0
}

// MockManager_Cluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cluster'
type MockManager_Cluster_Call struct {
	*mock.Call
}

// Cluster is a helper method to define mock.On call
func (_e *MockManager_Expecter) Cluster() *MockManager_Cluster_Call {
	return &MockManager_Cluster_Call{Call: _e.mock.On("Cluster")}
}

func (_c *MockManager_Cluster_Call) Run(run func()) *MockManager_Cluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Cluster_Call) Return(_a0 resource.ClusterResourceService) *MockManager_Cluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Cluster_Call) RunAndReturn(run func() resource.ClusterResourceService) *MockManager_Cluster_Call {
	_c.Call.Return(run)
	return _c
}

// Converter provides a mock function with no fields
func (_m *MockManager) Converter() resource.ResourceConverter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Converter")
	}

	var r0 resource.ResourceConverter
	if rf, ok := ret.Get(0).(func() resource.ResourceConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ResourceConverter)
		}
	}

	return r0
}

// MockManager_Converter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Converter'
type MockManager_Converter_Call struct {
	*mock.Call
}

// Converter is a helper method to define mock.On call
func (_e *MockManager_Expecter) Converter() *MockManager_Converter_Call {
	return &MockManager_Converter_Call{Call: _e.mock.On("Converter")}
}

func (_c *MockManager_Converter_Call) Run(run func()) *MockManager_Converter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Converter_Call) Return(_a0 resource.ResourceConverter) *MockManager_Converter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Converter_Call) RunAndReturn(run func() resource.ResourceConverter) *MockManager_Converter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
