// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "github.com/supabase-community/gotrue-go/types"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AdminCreateUser provides a mock function with given fields: params
func (_m *MockClient) AdminCreateUser(params types.AdminCreateUserRequest) (*types.AdminCreateUserResponse, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for AdminCreateUser")
	}

	var r0 *types.AdminCreateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(types.AdminCreateUserRequest) (*types.AdminCreateUserResponse, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(types.AdminCreateUserRequest) *types.AdminCreateUserResponse); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AdminCreateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(types.AdminCreateUserRequest) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_AdminCreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminCreateUser'
type MockClient_AdminCreateUser_Call struct {
	*mock.Call
}

// AdminCreateUser is a helper method to define mock.On call
//   - params types.AdminCreateUserRequest
func (_e *MockClient_Expecter) AdminCreateUser(params interface{}) *MockClient_AdminCreateUser_Call {
	return &MockClient_AdminCreateUser_Call{Call: _e.mock.On("AdminCreateUser", params)}
}

func (_c *MockClient_AdminCreateUser_Call) Run(run func(params types.AdminCreateUserRequest)) *MockClient_AdminCreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.AdminCreateUserRequest))
	})
	return _c
}

func (_c *MockClient_AdminCreateUser_Call) Return(_a0 *types.AdminCreateUserResponse, _a1 error) *MockClient_AdminCreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_AdminCreateUser_Call) RunAndReturn(run func(types.AdminCreateUserRequest) (*types.AdminCreateUserResponse, error)) *MockClient_AdminCreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// AdminDeleteUser provides a mock function with given fields: req
func (_m *MockClient) AdminDeleteUser(req types.AdminDeleteUserRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for AdminDeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.AdminDeleteUserRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_AdminDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminDeleteUser'
type MockClient_AdminDeleteUser_Call struct {
	*mock.Call
}

// AdminDeleteUser is a helper method to define mock.On call
//   - req types.AdminDeleteUserRequest
func (_e *MockClient_Expecter) AdminDeleteUser(req interface{}) *MockClient_AdminDeleteUser_Call {
	return &MockClient_AdminDeleteUser_Call{Call: _e.mock.On("AdminDeleteUser", req)}
}

func (_c *MockClient_AdminDeleteUser_Call) Run(run func(req types.AdminDeleteUserRequest)) *MockClient_AdminDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.AdminDeleteUserRequest))
	})
	return _c
}

func (_c *MockClient_AdminDeleteUser_Call) Return(_a0 error) *MockClient_AdminDeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_AdminDeleteUser_Call) RunAndReturn(run func(types.AdminDeleteUserRequest) error) *MockClient_AdminDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// AdminUpdateUser provides a mock function with given fields: req
func (_m *MockClient) AdminUpdateUser(req types.AdminUpdateUserRequest) (*types.AdminUpdateUserResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdateUser")
	}

	var r0 *types.AdminUpdateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(types.AdminUpdateUserRequest) (*types.AdminUpdateUserResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(types.AdminUpdateUserRequest) *types.AdminUpdateUserResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AdminUpdateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(types.AdminUpdateUserRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_AdminUpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateUser'
type MockClient_AdminUpdateUser_Call struct {
	*mock.Call
}

// AdminUpdateUser is a helper method to define mock.On call
//   - req types.AdminUpdateUserRequest
func (_e *MockClient_Expecter) AdminUpdateUser(req interface{}) *MockClient_AdminUpdateUser_Call {
	return &MockClient_AdminUpdateUser_Call{Call: _e.mock.On("AdminUpdateUser", req)}
}

func (_c *MockClient_AdminUpdateUser_Call) Run(run func(req types.AdminUpdateUserRequest)) *MockClient_AdminUpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.AdminUpdateUserRequest))
	})
	return _c
}

func (_c *MockClient_AdminUpdateUser_Call) Return(_a0 *types.AdminUpdateUserResponse, _a1 error) *MockClient_AdminUpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_AdminUpdateUser_Call) RunAndReturn(run func(types.AdminUpdateUserRequest) (*types.AdminUpdateUserResponse, error)) *MockClient_AdminUpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
