// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/neutree-ai/neutree/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionIssuer is an autogenerated mock type for the SessionIssuer type
type MockSessionIssuer struct {
	mock.Mock
}

type MockSessionIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionIssuer) EXPECT() *MockSessionIssuer_Expecter {
	return &MockSessionIssuer_Expecter{mock: &_m.Mock}
}

// GenerateMagicLink provides a mock function with given fields: ctx, email
func (_m *MockSessionIssuer) GenerateMagicLink(ctx context.Context, email string) (*auth.MagicLink, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMagicLink")
	}

	var r0 *auth.MagicLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.MagicLink, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.MagicLink); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.MagicLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionIssuer_GenerateMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMagicLink'
type MockSessionIssuer_GenerateMagicLink_Call struct {
	*mock.Call
}

// GenerateMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockSessionIssuer_Expecter) GenerateMagicLink(ctx interface{}, email interface{}) *MockSessionIssuer_GenerateMagicLink_Call {
	return &MockSessionIssuer_GenerateMagicLink_Call{Call: _e.mock.On("GenerateMagicLink", ctx, email)}
}

func (_c *MockSessionIssuer_GenerateMagicLink_Call) Run(run func(ctx context.Context, email string)) *MockSessionIssuer_GenerateMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionIssuer_GenerateMagicLink_Call) Return(_a0 *auth.MagicLink, _a1 error) *MockSessionIssuer_GenerateMagicLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionIssuer_GenerateMagicLink_Call) RunAndReturn(run func(context.Context, string) (*auth.MagicLink, error)) *MockSessionIssuer_GenerateMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMagicLink provides a mock function with given fields: ctx, hashedToken
func (_m *MockSessionIssuer) VerifyMagicLink(ctx context.Context, hashedToken string) ([]byte, error) {
	ret := _m.Called(ctx, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMagicLink")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, hashedToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, hashedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hashedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionIssuer_VerifyMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMagicLink'
type MockSessionIssuer_VerifyMagicLink_Call struct {
	*mock.Call
}

// VerifyMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedToken string
func (_e *MockSessionIssuer_Expecter) VerifyMagicLink(ctx interface{}, hashedToken interface{}) *MockSessionIssuer_VerifyMagicLink_Call {
	return &MockSessionIssuer_VerifyMagicLink_Call{Call: _e.mock.On("VerifyMagicLink", ctx, hashedToken)}
}

func (_c *MockSessionIssuer_VerifyMagicLink_Call) Run(run func(ctx context.Context, hashedToken string)) *MockSessionIssuer_VerifyMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionIssuer_VerifyMagicLink_Call) Return(_a0 []byte, _a1 error) *MockSessionIssuer_VerifyMagicLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionIssuer_VerifyMagicLink_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockSessionIssuer_VerifyMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionIssuer creates a new instance of MockSessionIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionIssuer {
	mock := &MockSessionIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
