FROM python:3.12-slim

ARG CLUSTER_VERSION=""
LABEL neutree.ai/cluster-version="${CLUSTER_VERSION}"

WORKDIR /app

COPY python/router/requirements.txt python/router/requirements.txt
RUN pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir -r python/router/requirements.txt

COPY python/router router

ENTRYPOINT ["python", "-m", "router"]
CMD []
