// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	io "io"

	model_registry "github.com/neutree-ai/neutree/pkg/model_registry"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockModelRegistry is an autogenerated mock type for the ModelRegistry type
type MockModelRegistry struct {
	mock.Mock
}

type MockModelRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelRegistry) EXPECT() *MockModelRegistry_Expecter {
	return &MockModelRegistry_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with no fields
func (_m *MockModelRegistry) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockModelRegistry_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockModelRegistry_Expecter) Connect() *MockModelRegistry_Connect_Call {
	return &MockModelRegistry_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockModelRegistry_Connect_Call) Run(run func()) *MockModelRegistry_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModelRegistry_Connect_Call) Return(_a0 error) *MockModelRegistry_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_Connect_Call) RunAndReturn(run func() error) *MockModelRegistry_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteModel provides a mock function with given fields: name, version
func (_m *MockModelRegistry) DeleteModel(name string, version string) error {
	ret := _m.Called(name, version)

	if len(ret) == 0 {
		panic("no return value specified for DeleteModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_DeleteModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteModel'
type MockModelRegistry_DeleteModel_Call struct {
	*mock.Call
}

// DeleteModel is a helper method to define mock.On call
//   - name string
//   - version string
func (_e *MockModelRegistry_Expecter) DeleteModel(name interface{}, version interface{}) *MockModelRegistry_DeleteModel_Call {
	return &MockModelRegistry_DeleteModel_Call{Call: _e.mock.On("DeleteModel", name, version)}
}

func (_c *MockModelRegistry_DeleteModel_Call) Run(run func(name string, version string)) *MockModelRegistry_DeleteModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockModelRegistry_DeleteModel_Call) Return(_a0 error) *MockModelRegistry_DeleteModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_DeleteModel_Call) RunAndReturn(run func(string, string) error) *MockModelRegistry_DeleteModel_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *MockModelRegistry) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockModelRegistry_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *MockModelRegistry_Expecter) Disconnect() *MockModelRegistry_Disconnect_Call {
	return &MockModelRegistry_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *MockModelRegistry_Disconnect_Call) Run(run func()) *MockModelRegistry_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModelRegistry_Disconnect_Call) Return(_a0 error) *MockModelRegistry_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_Disconnect_Call) RunAndReturn(run func() error) *MockModelRegistry_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// ExportModel provides a mock function with given fields: name, version, outputPath
func (_m *MockModelRegistry) ExportModel(name string, version string, outputPath string) error {
	ret := _m.Called(name, version, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for ExportModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, version, outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_ExportModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportModel'
type MockModelRegistry_ExportModel_Call struct {
	*mock.Call
}

// ExportModel is a helper method to define mock.On call
//   - name string
//   - version string
//   - outputPath string
func (_e *MockModelRegistry_Expecter) ExportModel(name interface{}, version interface{}, outputPath interface{}) *MockModelRegistry_ExportModel_Call {
	return &MockModelRegistry_ExportModel_Call{Call: _e.mock.On("ExportModel", name, version, outputPath)}
}

func (_c *MockModelRegistry_ExportModel_Call) Run(run func(name string, version string, outputPath string)) *MockModelRegistry_ExportModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockModelRegistry_ExportModel_Call) Return(_a0 error) *MockModelRegistry_ExportModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_ExportModel_Call) RunAndReturn(run func(string, string, string) error) *MockModelRegistry_ExportModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelPath provides a mock function with given fields: name, version
func (_m *MockModelRegistry) GetModelPath(name string, version string) (string, error) {
	ret := _m.Called(name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetModelPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(name, version)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, version)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRegistry_GetModelPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelPath'
type MockModelRegistry_GetModelPath_Call struct {
	*mock.Call
}

// GetModelPath is a helper method to define mock.On call
//   - name string
//   - version string
func (_e *MockModelRegistry_Expecter) GetModelPath(name interface{}, version interface{}) *MockModelRegistry_GetModelPath_Call {
	return &MockModelRegistry_GetModelPath_Call{Call: _e.mock.On("GetModelPath", name, version)}
}

func (_c *MockModelRegistry_GetModelPath_Call) Run(run func(name string, version string)) *MockModelRegistry_GetModelPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockModelRegistry_GetModelPath_Call) Return(_a0 string, _a1 error) *MockModelRegistry_GetModelPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRegistry_GetModelPath_Call) RunAndReturn(run func(string, string) (string, error)) *MockModelRegistry_GetModelPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelVersion provides a mock function with given fields: name, version
func (_m *MockModelRegistry) GetModelVersion(name string, version string) (*v1.ModelVersion, error) {
	ret := _m.Called(name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetModelVersion")
	}

	var r0 *v1.ModelVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*v1.ModelVersion, error)); ok {
		return rf(name, version)
	}
	if rf, ok := ret.Get(0).(func(string, string) *v1.ModelVersion); ok {
		r0 = rf(name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ModelVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRegistry_GetModelVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelVersion'
type MockModelRegistry_GetModelVersion_Call struct {
	*mock.Call
}

// GetModelVersion is a helper method to define mock.On call
//   - name string
//   - version string
func (_e *MockModelRegistry_Expecter) GetModelVersion(name interface{}, version interface{}) *MockModelRegistry_GetModelVersion_Call {
	return &MockModelRegistry_GetModelVersion_Call{Call: _e.mock.On("GetModelVersion", name, version)}
}

func (_c *MockModelRegistry_GetModelVersion_Call) Run(run func(name string, version string)) *MockModelRegistry_GetModelVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockModelRegistry_GetModelVersion_Call) Return(_a0 *v1.ModelVersion, _a1 error) *MockModelRegistry_GetModelVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRegistry_GetModelVersion_Call) RunAndReturn(run func(string, string) (*v1.ModelVersion, error)) *MockModelRegistry_GetModelVersion_Call {
	_c.Call.Return(run)
	return _c
}

// HealthyCheck provides a mock function with no fields
func (_m *MockModelRegistry) HealthyCheck() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthyCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_HealthyCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthyCheck'
type MockModelRegistry_HealthyCheck_Call struct {
	*mock.Call
}

// HealthyCheck is a helper method to define mock.On call
func (_e *MockModelRegistry_Expecter) HealthyCheck() *MockModelRegistry_HealthyCheck_Call {
	return &MockModelRegistry_HealthyCheck_Call{Call: _e.mock.On("HealthyCheck")}
}

func (_c *MockModelRegistry_HealthyCheck_Call) Run(run func()) *MockModelRegistry_HealthyCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModelRegistry_HealthyCheck_Call) Return(_a0 error) *MockModelRegistry_HealthyCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_HealthyCheck_Call) RunAndReturn(run func() error) *MockModelRegistry_HealthyCheck_Call {
	_c.Call.Return(run)
	return _c
}

// ImportModel provides a mock function with given fields: reader, name, version, progress
func (_m *MockModelRegistry) ImportModel(reader io.Reader, name string, version string, progress io.Writer) error {
	ret := _m.Called(reader, name, version, progress)

	if len(ret) == 0 {
		panic("no return value specified for ImportModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, string, string, io.Writer) error); ok {
		r0 = rf(reader, name, version, progress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelRegistry_ImportModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportModel'
type MockModelRegistry_ImportModel_Call struct {
	*mock.Call
}

// ImportModel is a helper method to define mock.On call
//   - reader io.Reader
//   - name string
//   - version string
//   - progress io.Writer
func (_e *MockModelRegistry_Expecter) ImportModel(reader interface{}, name interface{}, version interface{}, progress interface{}) *MockModelRegistry_ImportModel_Call {
	return &MockModelRegistry_ImportModel_Call{Call: _e.mock.On("ImportModel", reader, name, version, progress)}
}

func (_c *MockModelRegistry_ImportModel_Call) Run(run func(reader io.Reader, name string, version string, progress io.Writer)) *MockModelRegistry_ImportModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(string), args[2].(string), args[3].(io.Writer))
	})
	return _c
}

func (_c *MockModelRegistry_ImportModel_Call) Return(_a0 error) *MockModelRegistry_ImportModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelRegistry_ImportModel_Call) RunAndReturn(run func(io.Reader, string, string, io.Writer) error) *MockModelRegistry_ImportModel_Call {
	_c.Call.Return(run)
	return _c
}

// ListModels provides a mock function with given fields: option
func (_m *MockModelRegistry) ListModels(option model_registry.ListOption) ([]v1.GeneralModel, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 []v1.GeneralModel
	var r1 error
	if rf, ok := ret.Get(0).(func(model_registry.ListOption) ([]v1.GeneralModel, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(model_registry.ListOption) []v1.GeneralModel); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.GeneralModel)
		}
	}

	if rf, ok := ret.Get(1).(func(model_registry.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRegistry_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockModelRegistry_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - option model_registry.ListOption
func (_e *MockModelRegistry_Expecter) ListModels(option interface{}) *MockModelRegistry_ListModels_Call {
	return &MockModelRegistry_ListModels_Call{Call: _e.mock.On("ListModels", option)}
}

func (_c *MockModelRegistry_ListModels_Call) Run(run func(option model_registry.ListOption)) *MockModelRegistry_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model_registry.ListOption))
	})
	return _c
}

func (_c *MockModelRegistry_ListModels_Call) Return(_a0 []v1.GeneralModel, _a1 error) *MockModelRegistry_ListModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRegistry_ListModels_Call) RunAndReturn(run func(model_registry.ListOption) ([]v1.GeneralModel, error)) *MockModelRegistry_ListModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelRegistry creates a new instance of MockModelRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelRegistry {
	mock := &MockModelRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
