package e2e

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/neutree-ai/neutree/internal/ray/dashboard"
)

// RayHelper provides Ray Dashboard API access for e2e tests.
type RayHelper struct {
	dashboardURL string
	service      dashboard.DashboardService
}

// NewRayHelper creates a RayHelper from a cluster dashboard URL.
func NewRayHelper(dashboardURL string) *RayHelper {
	return &RayHelper{
		dashboardURL: dashboardURL,
		service:      dashboard.NewDashboardService(dashboardURL),
	}
}

// GetServeApplications retrieves the current Ray Serve applications and their config.
func (h *RayHelper) GetServeApplications() (*dashboard.RayServeApplicationsResponse, error) {
	return h.service.GetServeApplications()
}

// GetApplicationConfig returns the deployed config for a specific application name.
// Returns (nil, nil) if not found.
func (h *RayHelper) GetApplicationConfig(appName string) (*dashboard.RayServeApplication, error) {
	apps, err := h.service.GetServeApplications()
	if err != nil {
		return nil, err
	}

	if appStatus, ok := apps.Applications[appName]; ok {
		return appStatus.DeployedAppConfig, nil
	}

	return nil, nil
}

// GetApplicationDeployments returns the deployments for a specific application.
// Returns (nil, nil) if not found.
func (h *RayHelper) GetApplicationDeployments(appName string) (map[string]dashboard.Deployment, error) {
	apps, err := h.service.GetServeApplications()
	if err != nil {
		return nil, err
	}

	if appStatus, ok := apps.Applications[appName]; ok {
		return appStatus.Deployments, nil
	}

	return nil, nil
}

// RuntimeDeploymentConfig represents the actual deployment config from Ray Serve
// runtime status (applications.<app>.deployments.<name>.deployment_config).
// This is generated by app.py from the application-level args.deployment_options.
type RuntimeDeploymentConfig struct {
	Name            string                 `json:"name"`
	NumReplicas     json.Number            `json:"num_replicas"`
	RayActorOptions RuntimeRayActorOptions `json:"ray_actor_options"`
}

// RuntimeRayActorOptions holds the actual Ray actor resource config from runtime deployments.
type RuntimeRayActorOptions struct {
	NumCPUs    float64                `json:"num_cpus"`
	NumGPUs    float64                `json:"num_gpus"`
	Memory     float64                `json:"memory"`
	Resources  map[string]float64     `json:"resources"`
	RuntimeEnv map[string]interface{} `json:"runtime_env"`
}

// RuntimeDeployment represents a single deployment from the runtime status.
type RuntimeDeployment struct {
	Name             string                  `json:"name"`
	Status           string                  `json:"status"`
	DeploymentConfig RuntimeDeploymentConfig `json:"deployment_config"`
}

type rawAppStatus struct {
	Deployments map[string]RuntimeDeployment `json:"deployments"`
}

type rawServeResponse struct {
	Applications map[string]rawAppStatus `json:"applications"`
}

// GetRuntimeDeployments fetches Ray Serve applications via raw HTTP and returns
// the runtime deployment configs (Backend, Controller) for each application.
// These represent the actual configs generated by app.py, not the input args.
func (h *RayHelper) GetRuntimeDeployments() (map[string]map[string]RuntimeDeployment, error) {
	url := h.dashboardURL + "/api/serve/applications/"

	client := &http.Client{Timeout: 30 * time.Second}

	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %d from %s", resp.StatusCode, url)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	var raw rawServeResponse
	if err := json.Unmarshal(body, &raw); err != nil {
		return nil, fmt.Errorf("failed to parse Ray Serve response: %w", err)
	}

	result := make(map[string]map[string]RuntimeDeployment)

	for appName, appStatus := range raw.Applications {
		if len(appStatus.Deployments) > 0 {
			result[appName] = appStatus.Deployments
		}
	}

	return result, nil
}

// GetAppRuntimeDeployments returns the runtime deployments for a specific endpoint.
// Application name in Ray Serve is "<workspace>_<endpoint-name>".
func (h *RayHelper) GetAppRuntimeDeployments(workspace, endpointName string) (map[string]RuntimeDeployment, error) {
	appName := workspace + "_" + endpointName

	allDeps, err := h.GetRuntimeDeployments()
	if err != nil {
		return nil, err
	}

	if deps, ok := allDeps[appName]; ok {
		return deps, nil
	}

	return nil, fmt.Errorf("application %s not found in Ray Serve", appName)
}

// ListNodes retrieves the list of Ray nodes from the dashboard.
func (h *RayHelper) ListNodes() (int, error) {
	nodes, err := h.service.ListNodes()
	if err != nil {
		return 0, err
	}

	return len(nodes), nil
}
