package e2e

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/neutree-ai/neutree/internal/ray/dashboard"
)

// RayHelper provides Ray Dashboard API access for e2e tests.
type RayHelper struct {
	dashboardURL string
	service      dashboard.DashboardService
}

// NewRayHelper creates a RayHelper from a cluster dashboard URL.
func NewRayHelper(dashboardURL string) *RayHelper {
	return &RayHelper{
		dashboardURL: dashboardURL,
		service:      dashboard.NewDashboardService(dashboardURL),
	}
}

// GetServeApplications retrieves the current Ray Serve applications and their config.
func (h *RayHelper) GetServeApplications() (*dashboard.RayServeApplicationsResponse, error) {
	return h.service.GetServeApplications()
}

// GetApplicationConfig returns the deployed config for a specific application name.
// Returns (nil, nil) if not found.
func (h *RayHelper) GetApplicationConfig(appName string) (*dashboard.RayServeApplication, error) {
	apps, err := h.service.GetServeApplications()
	if err != nil {
		return nil, err
	}

	if appStatus, ok := apps.Applications[appName]; ok {
		return appStatus.DeployedAppConfig, nil
	}

	return nil, nil
}

// GetApplicationDeployments returns the deployments for a specific application.
// Returns (nil, nil) if not found.
func (h *RayHelper) GetApplicationDeployments(appName string) (map[string]dashboard.Deployment, error) {
	apps, err := h.service.GetServeApplications()
	if err != nil {
		return nil, err
	}

	if appStatus, ok := apps.Applications[appName]; ok {
		return appStatus.Deployments, nil
	}

	return nil, nil
}

// RuntimeDeploymentConfig represents the actual deployment config from Ray Serve
// runtime status (applications.<app>.deployments.<name>.deployment_config).
// This is generated by app.py from the application-level args.deployment_options.
type RuntimeDeploymentConfig struct {
	Name            string                 `json:"name"`
	NumReplicas     json.Number            `json:"num_replicas"`
	RayActorOptions RuntimeRayActorOptions `json:"ray_actor_options"`
}

// RuntimeRayActorOptions holds the actual Ray actor resource config from runtime deployments.
type RuntimeRayActorOptions struct {
	NumCPUs    float64                `json:"num_cpus"`
	NumGPUs    float64                `json:"num_gpus"`
	Memory     float64                `json:"memory"`
	Resources  map[string]float64     `json:"resources"`
	RuntimeEnv map[string]interface{} `json:"runtime_env"`
}

// RuntimeDeployment represents a single deployment from the runtime status.
type RuntimeDeployment struct {
	Name             string                  `json:"name"`
	Status           string                  `json:"status"`
	DeploymentConfig RuntimeDeploymentConfig `json:"deployment_config"`
}

type rawAppStatus struct {
	Deployments map[string]RuntimeDeployment `json:"deployments"`
}

type rawServeResponse struct {
	Applications map[string]rawAppStatus `json:"applications"`
}

// getServeApplicationsRaw fetches the Ray Serve applications endpoint and returns
// the response body untouched. Callers that need a field the typed client does
// not model decode it themselves.
func (h *RayHelper) getServeApplicationsRaw() ([]byte, error) {
	url := h.dashboardURL + "/api/serve/applications/"

	client := &http.Client{Timeout: 30 * time.Second}

	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %d from %s", resp.StatusCode, url)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	return body, nil
}

// GetRuntimeDeployments fetches Ray Serve applications via raw HTTP and returns
// the runtime deployment configs (Backend, Controller) for each application.
// These represent the actual configs generated by app.py, not the input args.
func (h *RayHelper) GetRuntimeDeployments() (map[string]map[string]RuntimeDeployment, error) {
	body, err := h.getServeApplicationsRaw()
	if err != nil {
		return nil, err
	}

	var raw rawServeResponse
	if err := json.Unmarshal(body, &raw); err != nil {
		return nil, fmt.Errorf("failed to parse Ray Serve response: %w", err)
	}

	result := make(map[string]map[string]RuntimeDeployment)

	for appName, appStatus := range raw.Applications {
		if len(appStatus.Deployments) > 0 {
			result[appName] = appStatus.Deployments
		}
	}

	return result, nil
}

// GetAppRuntimeDeployments returns the runtime deployments for a specific endpoint.
// Application name in Ray Serve is "<workspace>_<endpoint-name>".
func (h *RayHelper) GetAppRuntimeDeployments(workspace, endpointName string) (map[string]RuntimeDeployment, error) {
	appName := workspace + "_" + endpointName

	allDeps, err := h.GetRuntimeDeployments()
	if err != nil {
		return nil, err
	}

	if deps, ok := allDeps[appName]; ok {
		return deps, nil
	}

	return nil, fmt.Errorf("application %s not found in Ray Serve", appName)
}

// ServeAppSnapshot is the part of a Ray Serve application's status that answers
// "is this still the same deployment". It is what a test asserting that some
// unrelated write did not disturb a running endpoint compares before and after.
type ServeAppSnapshot struct {
	// Name is the Ray Serve application name, "<workspace>_<endpoint>".
	Name string
	// Status is the application status, e.g. RUNNING.
	Status string
	// LastDeployedTimeS is when Ray last (re)deployed this application. It moves
	// on every redeploy and on nothing else, which is what makes it the
	// definitive "the Serve app was not redeployed" guard. Kept as the string
	// Ray sent so a float that round-trips imprecisely cannot look like a change.
	LastDeployedTimeS string
	// DeployedAppConfig is the config Ray echoes back, as its own bytes rather
	// than a decoded struct: "nothing in the orchestration path moved" has to
	// hold for every field the server sent, including ones this build does not
	// model. Byte equality is exactly "the same PUT is still live".
	DeployedAppConfig json.RawMessage
	// Args is deployed_app_config.args decoded, for naming the individual field
	// that moved when the byte comparison above fails.
	Args map[string]interface{}
}

type rawAppSnapshot struct {
	Status            string          `json:"status"`
	LastDeployedTimeS json.RawMessage `json:"last_deployed_time_s"`
	DeployedAppConfig json.RawMessage `json:"deployed_app_config"`
}

type rawServeSnapshotResponse struct {
	Applications map[string]rawAppSnapshot `json:"applications"`
}

// GetServeAppSnapshot returns the deployment identity of one Ray Serve
// application. It reports an error rather than a zero snapshot when the
// application is absent, so a caller cannot compare two empty snapshots and read
// that as "unchanged".
func (h *RayHelper) GetServeAppSnapshot(appName string) (*ServeAppSnapshot, error) {
	body, err := h.getServeApplicationsRaw()
	if err != nil {
		return nil, err
	}

	var raw rawServeSnapshotResponse
	if err := json.Unmarshal(body, &raw); err != nil {
		return nil, fmt.Errorf("failed to parse Ray Serve response: %w", err)
	}

	app, ok := raw.Applications[appName]
	if !ok {
		names := make([]string, 0, len(raw.Applications))
		for name := range raw.Applications {
			names = append(names, name)
		}

		sort.Strings(names)

		return nil, fmt.Errorf("application %q not found in Ray Serve; present: %v", appName, names)
	}

	snapshot := &ServeAppSnapshot{
		Name:              appName,
		Status:            app.Status,
		LastDeployedTimeS: string(app.LastDeployedTimeS),
		DeployedAppConfig: app.DeployedAppConfig,
	}

	if len(app.DeployedAppConfig) > 0 {
		var config struct {
			Args map[string]interface{} `json:"args"`
		}

		if err := json.Unmarshal(app.DeployedAppConfig, &config); err != nil {
			return nil, fmt.Errorf("failed to parse deployed_app_config of %q: %w", appName, err)
		}

		snapshot.Args = config.Args
	}

	return snapshot, nil
}

// orchestrationPathFields are the deployed_app_config args that decide where a
// model is read from, what it is served as, and what the engine container runs
// with — the NFS mount among its run options.
//
// They are listed rather than derived so a failure can name the one that moved.
// The whole-config comparison a caller should make alongside them is what covers
// a field nobody thought to list.
var orchestrationPathFields = []string{
	"model.registry_type",
	"model.name",
	"model.version",
	"model.file",
	"model.task",
	"model.serve_name",
	"model.registry_path",
	"model.path",
	"backend_container.image",
	"backend_container.run_options",
}

// orchestrationPathValue reads one dotted field out of a snapshot's args,
// rendered as JSON so a nested value — the container run options, which carry
// the NFS mount — compares as a whole. A missing field renders as the empty
// string, which is why callers gate on the fields being present first.
func orchestrationPathValue(snapshot *ServeAppSnapshot, path string) string {
	if snapshot == nil {
		return ""
	}

	var current any = snapshot.Args

	for _, key := range strings.Split(path, ".") {
		node, ok := current.(map[string]interface{})
		if !ok {
			return ""
		}

		current, ok = node[key]
		if !ok {
			return ""
		}
	}

	encoded, err := json.Marshal(current)
	if err != nil {
		return ""
	}

	return string(encoded)
}

// requireOrchestrationPath asserts that a snapshot actually describes a running
// model deployment, and returns the engine image it names.
//
// This is the gate in front of every comparison a caller makes with the
// snapshot. Each field below is one that would be absent — and would therefore
// compare equal to an equally absent one on the other side — if the endpoint were
// not deployed the way the case assumes: not running, not backed by a private
// NFS registry, or not using the per-endpoint engine container. Without it, a
// misconfigured environment reports "nothing changed" because nothing was ever
// observed.
func requireOrchestrationPath(snapshot *ServeAppSnapshot) string {
	GinkgoHelper()

	Expect(snapshot).NotTo(BeNil(), "no Ray Serve application snapshot to assert against")
	Expect(snapshot.Status).To(Equal("RUNNING"),
		"Ray Serve application %s is %q, not RUNNING", snapshot.Name, snapshot.Status)
	Expect(snapshot.Args).NotTo(BeEmpty(),
		"Ray Serve application %s has no deployed_app_config args", snapshot.Name)
	Expect(snapshot.LastDeployedTimeS).NotTo(BeElementOf("", "null", "0"),
		"Ray Serve application %s reports no last_deployed_time_s, so a comparison of it "+
			"would not detect a redeploy", snapshot.Name)

	for _, field := range orchestrationPathFields {
		Expect(orchestrationPathValue(snapshot, field)).NotTo(BeElementOf("", "null", `""`),
			"orchestration path field %s is not set on Ray Serve application %s; comparing it "+
				"before and after would pass without observing anything",
			field, snapshot.Name)
	}

	image, ok := orchestrationPathString(snapshot, "backend_container.image")
	Expect(ok).To(BeTrue(), "backend_container.image is not a string on %s", snapshot.Name)

	return image
}

// orchestrationPathString reads a dotted field expected to hold a plain string.
func orchestrationPathString(snapshot *ServeAppSnapshot, path string) (string, bool) {
	var value string
	if err := json.Unmarshal([]byte(orchestrationPathValue(snapshot, path)), &value); err != nil {
		return "", false
	}

	return value, true
}

// ListNodes retrieves the list of Ray nodes from the dashboard.
func (h *RayHelper) ListNodes() (int, error) {
	nodes, err := h.service.ListNodes()
	if err != nil {
		return 0, err
	}

	return len(nodes), nil
}
