// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	storage "github.com/neutree-ai/neutree/pkg/storage"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateImageRegistry provides a mock function with given fields: data
func (_m *MockStorage) CreateImageRegistry(data *v1.ImageRegistry) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ImageRegistry) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImageRegistry'
type MockStorage_CreateImageRegistry_Call struct {
	*mock.Call
}

// CreateImageRegistry is a helper method to define mock.On call
//   - data *v1.ImageRegistry
func (_e *MockStorage_Expecter) CreateImageRegistry(data interface{}) *MockStorage_CreateImageRegistry_Call {
	return &MockStorage_CreateImageRegistry_Call{Call: _e.mock.On("CreateImageRegistry", data)}
}

func (_c *MockStorage_CreateImageRegistry_Call) Run(run func(data *v1.ImageRegistry)) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ImageRegistry))
	})
	return _c
}

func (_c *MockStorage_CreateImageRegistry_Call) Return(_a0 error) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateImageRegistry_Call) RunAndReturn(run func(*v1.ImageRegistry) error) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateModelRegistry provides a mock function with given fields: data
func (_m *MockStorage) CreateModelRegistry(data *v1.ModelRegistry) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ModelRegistry) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateModelRegistry'
type MockStorage_CreateModelRegistry_Call struct {
	*mock.Call
}

// CreateModelRegistry is a helper method to define mock.On call
//   - data *v1.ModelRegistry
func (_e *MockStorage_Expecter) CreateModelRegistry(data interface{}) *MockStorage_CreateModelRegistry_Call {
	return &MockStorage_CreateModelRegistry_Call{Call: _e.mock.On("CreateModelRegistry", data)}
}

func (_c *MockStorage_CreateModelRegistry_Call) Run(run func(data *v1.ModelRegistry)) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ModelRegistry))
	})
	return _c
}

func (_c *MockStorage_CreateModelRegistry_Call) Return(_a0 error) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateModelRegistry_Call) RunAndReturn(run func(*v1.ModelRegistry) error) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImageRegistry provides a mock function with given fields: id
func (_m *MockStorage) DeleteImageRegistry(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageRegistry'
type MockStorage_DeleteImageRegistry_Call struct {
	*mock.Call
}

// DeleteImageRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteImageRegistry(id interface{}) *MockStorage_DeleteImageRegistry_Call {
	return &MockStorage_DeleteImageRegistry_Call{Call: _e.mock.On("DeleteImageRegistry", id)}
}

func (_c *MockStorage_DeleteImageRegistry_Call) Run(run func(id string)) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteImageRegistry_Call) Return(_a0 error) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteImageRegistry_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteModelRegistry provides a mock function with given fields: id
func (_m *MockStorage) DeleteModelRegistry(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteModelRegistry'
type MockStorage_DeleteModelRegistry_Call struct {
	*mock.Call
}

// DeleteModelRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteModelRegistry(id interface{}) *MockStorage_DeleteModelRegistry_Call {
	return &MockStorage_DeleteModelRegistry_Call{Call: _e.mock.On("DeleteModelRegistry", id)}
}

func (_c *MockStorage_DeleteModelRegistry_Call) Run(run func(id string)) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteModelRegistry_Call) Return(_a0 error) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteModelRegistry_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// ListImageRegistry provides a mock function with given fields: option
func (_m *MockStorage) ListImageRegistry(option storage.ListOption) ([]v1.ImageRegistry, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListImageRegistry")
	}

	var r0 []v1.ImageRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ImageRegistry, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ImageRegistry); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ImageRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImageRegistry'
type MockStorage_ListImageRegistry_Call struct {
	*mock.Call
}

// ListImageRegistry is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListImageRegistry(option interface{}) *MockStorage_ListImageRegistry_Call {
	return &MockStorage_ListImageRegistry_Call{Call: _e.mock.On("ListImageRegistry", option)}
}

func (_c *MockStorage_ListImageRegistry_Call) Run(run func(option storage.ListOption)) *MockStorage_ListImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListImageRegistry_Call) Return(_a0 []v1.ImageRegistry, _a1 error) *MockStorage_ListImageRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListImageRegistry_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ImageRegistry, error)) *MockStorage_ListImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// ListModelRegistry provides a mock function with given fields: option
func (_m *MockStorage) ListModelRegistry(option storage.ListOption) ([]v1.ModelRegistry, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListModelRegistry")
	}

	var r0 []v1.ModelRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ModelRegistry, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ModelRegistry); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ModelRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModelRegistry'
type MockStorage_ListModelRegistry_Call struct {
	*mock.Call
}

// ListModelRegistry is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListModelRegistry(option interface{}) *MockStorage_ListModelRegistry_Call {
	return &MockStorage_ListModelRegistry_Call{Call: _e.mock.On("ListModelRegistry", option)}
}

func (_c *MockStorage_ListModelRegistry_Call) Run(run func(option storage.ListOption)) *MockStorage_ListModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListModelRegistry_Call) Return(_a0 []v1.ModelRegistry, _a1 error) *MockStorage_ListModelRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListModelRegistry_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ModelRegistry, error)) *MockStorage_ListModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImageRegistry provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateImageRegistry(id string, data *v1.ImageRegistry) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ImageRegistry) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImageRegistry'
type MockStorage_UpdateImageRegistry_Call struct {
	*mock.Call
}

// UpdateImageRegistry is a helper method to define mock.On call
//   - id string
//   - data *v1.ImageRegistry
func (_e *MockStorage_Expecter) UpdateImageRegistry(id interface{}, data interface{}) *MockStorage_UpdateImageRegistry_Call {
	return &MockStorage_UpdateImageRegistry_Call{Call: _e.mock.On("UpdateImageRegistry", id, data)}
}

func (_c *MockStorage_UpdateImageRegistry_Call) Run(run func(id string, data *v1.ImageRegistry)) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ImageRegistry))
	})
	return _c
}

func (_c *MockStorage_UpdateImageRegistry_Call) Return(_a0 error) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateImageRegistry_Call) RunAndReturn(run func(string, *v1.ImageRegistry) error) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateModelRegistry provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateModelRegistry(id string, data *v1.ModelRegistry) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ModelRegistry) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateModelRegistry'
type MockStorage_UpdateModelRegistry_Call struct {
	*mock.Call
}

// UpdateModelRegistry is a helper method to define mock.On call
//   - id string
//   - data *v1.ModelRegistry
func (_e *MockStorage_Expecter) UpdateModelRegistry(id interface{}, data interface{}) *MockStorage_UpdateModelRegistry_Call {
	return &MockStorage_UpdateModelRegistry_Call{Call: _e.mock.On("UpdateModelRegistry", id, data)}
}

func (_c *MockStorage_UpdateModelRegistry_Call) Run(run func(id string, data *v1.ModelRegistry)) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ModelRegistry))
	})
	return _c
}

func (_c *MockStorage_UpdateModelRegistry_Call) Return(_a0 error) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateModelRegistry_Call) RunAndReturn(run func(string, *v1.ModelRegistry) error) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
