// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	storage "github.com/neutree-ai/neutree/pkg/storage"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CallDatabaseFunction provides a mock function with given fields: name, params, result
func (_m *MockStorage) CallDatabaseFunction(name string, params map[string]interface{}, result interface{}) error {
	ret := _m.Called(name, params, result)

	if len(ret) == 0 {
		panic("no return value specified for CallDatabaseFunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}, interface{}) error); ok {
		r0 = rf(name, params, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CallDatabaseFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallDatabaseFunction'
type MockStorage_CallDatabaseFunction_Call struct {
	*mock.Call
}

// CallDatabaseFunction is a helper method to define mock.On call
//   - name string
//   - params map[string]interface{}
//   - result interface{}
func (_e *MockStorage_Expecter) CallDatabaseFunction(name interface{}, params interface{}, result interface{}) *MockStorage_CallDatabaseFunction_Call {
	return &MockStorage_CallDatabaseFunction_Call{Call: _e.mock.On("CallDatabaseFunction", name, params, result)}
}

func (_c *MockStorage_CallDatabaseFunction_Call) Run(run func(name string, params map[string]interface{}, result interface{})) *MockStorage_CallDatabaseFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]interface{}), args[2].(interface{}))
	})
	return _c
}

func (_c *MockStorage_CallDatabaseFunction_Call) Return(_a0 error) *MockStorage_CallDatabaseFunction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CallDatabaseFunction_Call) RunAndReturn(run func(string, map[string]interface{}, interface{}) error) *MockStorage_CallDatabaseFunction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateApiKey provides a mock function with given fields: data
func (_m *MockStorage) CreateApiKey(data *v1.ApiKey) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateApiKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ApiKey) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApiKey'
type MockStorage_CreateApiKey_Call struct {
	*mock.Call
}

// CreateApiKey is a helper method to define mock.On call
//   - data *v1.ApiKey
func (_e *MockStorage_Expecter) CreateApiKey(data interface{}) *MockStorage_CreateApiKey_Call {
	return &MockStorage_CreateApiKey_Call{Call: _e.mock.On("CreateApiKey", data)}
}

func (_c *MockStorage_CreateApiKey_Call) Run(run func(data *v1.ApiKey)) *MockStorage_CreateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ApiKey))
	})
	return _c
}

func (_c *MockStorage_CreateApiKey_Call) Return(_a0 error) *MockStorage_CreateApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateApiKey_Call) RunAndReturn(run func(*v1.ApiKey) error) *MockStorage_CreateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCluster provides a mock function with given fields: data
func (_m *MockStorage) CreateCluster(data *v1.Cluster) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Cluster) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type MockStorage_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - data *v1.Cluster
func (_e *MockStorage_Expecter) CreateCluster(data interface{}) *MockStorage_CreateCluster_Call {
	return &MockStorage_CreateCluster_Call{Call: _e.mock.On("CreateCluster", data)}
}

func (_c *MockStorage_CreateCluster_Call) Run(run func(data *v1.Cluster)) *MockStorage_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Cluster))
	})
	return _c
}

func (_c *MockStorage_CreateCluster_Call) Return(_a0 error) *MockStorage_CreateCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateCluster_Call) RunAndReturn(run func(*v1.Cluster) error) *MockStorage_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEndpoint provides a mock function with given fields: data
func (_m *MockStorage) CreateEndpoint(data *v1.Endpoint) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEndpoint'
type MockStorage_CreateEndpoint_Call struct {
	*mock.Call
}

// CreateEndpoint is a helper method to define mock.On call
//   - data *v1.Endpoint
func (_e *MockStorage_Expecter) CreateEndpoint(data interface{}) *MockStorage_CreateEndpoint_Call {
	return &MockStorage_CreateEndpoint_Call{Call: _e.mock.On("CreateEndpoint", data)}
}

func (_c *MockStorage_CreateEndpoint_Call) Run(run func(data *v1.Endpoint)) *MockStorage_CreateEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Endpoint))
	})
	return _c
}

func (_c *MockStorage_CreateEndpoint_Call) Return(_a0 error) *MockStorage_CreateEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateEndpoint_Call) RunAndReturn(run func(*v1.Endpoint) error) *MockStorage_CreateEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEngine provides a mock function with given fields: data
func (_m *MockStorage) CreateEngine(data *v1.Engine) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateEngine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Engine) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEngine'
type MockStorage_CreateEngine_Call struct {
	*mock.Call
}

// CreateEngine is a helper method to define mock.On call
//   - data *v1.Engine
func (_e *MockStorage_Expecter) CreateEngine(data interface{}) *MockStorage_CreateEngine_Call {
	return &MockStorage_CreateEngine_Call{Call: _e.mock.On("CreateEngine", data)}
}

func (_c *MockStorage_CreateEngine_Call) Run(run func(data *v1.Engine)) *MockStorage_CreateEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Engine))
	})
	return _c
}

func (_c *MockStorage_CreateEngine_Call) Return(_a0 error) *MockStorage_CreateEngine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateEngine_Call) RunAndReturn(run func(*v1.Engine) error) *MockStorage_CreateEngine_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImageRegistry provides a mock function with given fields: data
func (_m *MockStorage) CreateImageRegistry(data *v1.ImageRegistry) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ImageRegistry) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImageRegistry'
type MockStorage_CreateImageRegistry_Call struct {
	*mock.Call
}

// CreateImageRegistry is a helper method to define mock.On call
//   - data *v1.ImageRegistry
func (_e *MockStorage_Expecter) CreateImageRegistry(data interface{}) *MockStorage_CreateImageRegistry_Call {
	return &MockStorage_CreateImageRegistry_Call{Call: _e.mock.On("CreateImageRegistry", data)}
}

func (_c *MockStorage_CreateImageRegistry_Call) Run(run func(data *v1.ImageRegistry)) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ImageRegistry))
	})
	return _c
}

func (_c *MockStorage_CreateImageRegistry_Call) Return(_a0 error) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateImageRegistry_Call) RunAndReturn(run func(*v1.ImageRegistry) error) *MockStorage_CreateImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateModelCatalog provides a mock function with given fields: data
func (_m *MockStorage) CreateModelCatalog(data *v1.ModelCatalog) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateModelCatalog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ModelCatalog) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateModelCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateModelCatalog'
type MockStorage_CreateModelCatalog_Call struct {
	*mock.Call
}

// CreateModelCatalog is a helper method to define mock.On call
//   - data *v1.ModelCatalog
func (_e *MockStorage_Expecter) CreateModelCatalog(data interface{}) *MockStorage_CreateModelCatalog_Call {
	return &MockStorage_CreateModelCatalog_Call{Call: _e.mock.On("CreateModelCatalog", data)}
}

func (_c *MockStorage_CreateModelCatalog_Call) Run(run func(data *v1.ModelCatalog)) *MockStorage_CreateModelCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ModelCatalog))
	})
	return _c
}

func (_c *MockStorage_CreateModelCatalog_Call) Return(_a0 error) *MockStorage_CreateModelCatalog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateModelCatalog_Call) RunAndReturn(run func(*v1.ModelCatalog) error) *MockStorage_CreateModelCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateModelRegistry provides a mock function with given fields: data
func (_m *MockStorage) CreateModelRegistry(data *v1.ModelRegistry) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ModelRegistry) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateModelRegistry'
type MockStorage_CreateModelRegistry_Call struct {
	*mock.Call
}

// CreateModelRegistry is a helper method to define mock.On call
//   - data *v1.ModelRegistry
func (_e *MockStorage_Expecter) CreateModelRegistry(data interface{}) *MockStorage_CreateModelRegistry_Call {
	return &MockStorage_CreateModelRegistry_Call{Call: _e.mock.On("CreateModelRegistry", data)}
}

func (_c *MockStorage_CreateModelRegistry_Call) Run(run func(data *v1.ModelRegistry)) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.ModelRegistry))
	})
	return _c
}

func (_c *MockStorage_CreateModelRegistry_Call) Return(_a0 error) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateModelRegistry_Call) RunAndReturn(run func(*v1.ModelRegistry) error) *MockStorage_CreateModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function with given fields: data
func (_m *MockStorage) CreateRole(data *v1.Role) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Role) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockStorage_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - data *v1.Role
func (_e *MockStorage_Expecter) CreateRole(data interface{}) *MockStorage_CreateRole_Call {
	return &MockStorage_CreateRole_Call{Call: _e.mock.On("CreateRole", data)}
}

func (_c *MockStorage_CreateRole_Call) Run(run func(data *v1.Role)) *MockStorage_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Role))
	})
	return _c
}

func (_c *MockStorage_CreateRole_Call) Return(_a0 error) *MockStorage_CreateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateRole_Call) RunAndReturn(run func(*v1.Role) error) *MockStorage_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoleAssignment provides a mock function with given fields: data
func (_m *MockStorage) CreateRoleAssignment(data *v1.RoleAssignment) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoleAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.RoleAssignment) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateRoleAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoleAssignment'
type MockStorage_CreateRoleAssignment_Call struct {
	*mock.Call
}

// CreateRoleAssignment is a helper method to define mock.On call
//   - data *v1.RoleAssignment
func (_e *MockStorage_Expecter) CreateRoleAssignment(data interface{}) *MockStorage_CreateRoleAssignment_Call {
	return &MockStorage_CreateRoleAssignment_Call{Call: _e.mock.On("CreateRoleAssignment", data)}
}

func (_c *MockStorage_CreateRoleAssignment_Call) Run(run func(data *v1.RoleAssignment)) *MockStorage_CreateRoleAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.RoleAssignment))
	})
	return _c
}

func (_c *MockStorage_CreateRoleAssignment_Call) Return(_a0 error) *MockStorage_CreateRoleAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateRoleAssignment_Call) RunAndReturn(run func(*v1.RoleAssignment) error) *MockStorage_CreateRoleAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserProfile provides a mock function with given fields: data
func (_m *MockStorage) CreateUserProfile(data *v1.UserProfile) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.UserProfile) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserProfile'
type MockStorage_CreateUserProfile_Call struct {
	*mock.Call
}

// CreateUserProfile is a helper method to define mock.On call
//   - data *v1.UserProfile
func (_e *MockStorage_Expecter) CreateUserProfile(data interface{}) *MockStorage_CreateUserProfile_Call {
	return &MockStorage_CreateUserProfile_Call{Call: _e.mock.On("CreateUserProfile", data)}
}

func (_c *MockStorage_CreateUserProfile_Call) Run(run func(data *v1.UserProfile)) *MockStorage_CreateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.UserProfile))
	})
	return _c
}

func (_c *MockStorage_CreateUserProfile_Call) Return(_a0 error) *MockStorage_CreateUserProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateUserProfile_Call) RunAndReturn(run func(*v1.UserProfile) error) *MockStorage_CreateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkspace provides a mock function with given fields: data
func (_m *MockStorage) CreateWorkspace(data *v1.Workspace) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Workspace) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkspace'
type MockStorage_CreateWorkspace_Call struct {
	*mock.Call
}

// CreateWorkspace is a helper method to define mock.On call
//   - data *v1.Workspace
func (_e *MockStorage_Expecter) CreateWorkspace(data interface{}) *MockStorage_CreateWorkspace_Call {
	return &MockStorage_CreateWorkspace_Call{Call: _e.mock.On("CreateWorkspace", data)}
}

func (_c *MockStorage_CreateWorkspace_Call) Run(run func(data *v1.Workspace)) *MockStorage_CreateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Workspace))
	})
	return _c
}

func (_c *MockStorage_CreateWorkspace_Call) Return(_a0 error) *MockStorage_CreateWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateWorkspace_Call) RunAndReturn(run func(*v1.Workspace) error) *MockStorage_CreateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApiKey provides a mock function with given fields: id
func (_m *MockStorage) DeleteApiKey(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiKey'
type MockStorage_DeleteApiKey_Call struct {
	*mock.Call
}

// DeleteApiKey is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteApiKey(id interface{}) *MockStorage_DeleteApiKey_Call {
	return &MockStorage_DeleteApiKey_Call{Call: _e.mock.On("DeleteApiKey", id)}
}

func (_c *MockStorage_DeleteApiKey_Call) Run(run func(id string)) *MockStorage_DeleteApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteApiKey_Call) Return(_a0 error) *MockStorage_DeleteApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteApiKey_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function with given fields: id
func (_m *MockStorage) DeleteCluster(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type MockStorage_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteCluster(id interface{}) *MockStorage_DeleteCluster_Call {
	return &MockStorage_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", id)}
}

func (_c *MockStorage_DeleteCluster_Call) Run(run func(id string)) *MockStorage_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteCluster_Call) Return(_a0 error) *MockStorage_DeleteCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteCluster_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEndpoint provides a mock function with given fields: id
func (_m *MockStorage) DeleteEndpoint(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEndpoint'
type MockStorage_DeleteEndpoint_Call struct {
	*mock.Call
}

// DeleteEndpoint is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteEndpoint(id interface{}) *MockStorage_DeleteEndpoint_Call {
	return &MockStorage_DeleteEndpoint_Call{Call: _e.mock.On("DeleteEndpoint", id)}
}

func (_c *MockStorage_DeleteEndpoint_Call) Run(run func(id string)) *MockStorage_DeleteEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteEndpoint_Call) Return(_a0 error) *MockStorage_DeleteEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteEndpoint_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEngine provides a mock function with given fields: id
func (_m *MockStorage) DeleteEngine(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEngine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEngine'
type MockStorage_DeleteEngine_Call struct {
	*mock.Call
}

// DeleteEngine is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteEngine(id interface{}) *MockStorage_DeleteEngine_Call {
	return &MockStorage_DeleteEngine_Call{Call: _e.mock.On("DeleteEngine", id)}
}

func (_c *MockStorage_DeleteEngine_Call) Run(run func(id string)) *MockStorage_DeleteEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteEngine_Call) Return(_a0 error) *MockStorage_DeleteEngine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteEngine_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteEngine_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImageRegistry provides a mock function with given fields: id
func (_m *MockStorage) DeleteImageRegistry(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageRegistry'
type MockStorage_DeleteImageRegistry_Call struct {
	*mock.Call
}

// DeleteImageRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteImageRegistry(id interface{}) *MockStorage_DeleteImageRegistry_Call {
	return &MockStorage_DeleteImageRegistry_Call{Call: _e.mock.On("DeleteImageRegistry", id)}
}

func (_c *MockStorage_DeleteImageRegistry_Call) Run(run func(id string)) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteImageRegistry_Call) Return(_a0 error) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteImageRegistry_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteModelCatalog provides a mock function with given fields: id
func (_m *MockStorage) DeleteModelCatalog(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteModelCatalog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteModelCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteModelCatalog'
type MockStorage_DeleteModelCatalog_Call struct {
	*mock.Call
}

// DeleteModelCatalog is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteModelCatalog(id interface{}) *MockStorage_DeleteModelCatalog_Call {
	return &MockStorage_DeleteModelCatalog_Call{Call: _e.mock.On("DeleteModelCatalog", id)}
}

func (_c *MockStorage_DeleteModelCatalog_Call) Run(run func(id string)) *MockStorage_DeleteModelCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteModelCatalog_Call) Return(_a0 error) *MockStorage_DeleteModelCatalog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteModelCatalog_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteModelCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteModelRegistry provides a mock function with given fields: id
func (_m *MockStorage) DeleteModelRegistry(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteModelRegistry'
type MockStorage_DeleteModelRegistry_Call struct {
	*mock.Call
}

// DeleteModelRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteModelRegistry(id interface{}) *MockStorage_DeleteModelRegistry_Call {
	return &MockStorage_DeleteModelRegistry_Call{Call: _e.mock.On("DeleteModelRegistry", id)}
}

func (_c *MockStorage_DeleteModelRegistry_Call) Run(run func(id string)) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteModelRegistry_Call) Return(_a0 error) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteModelRegistry_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function with given fields: id
func (_m *MockStorage) DeleteRole(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockStorage_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteRole(id interface{}) *MockStorage_DeleteRole_Call {
	return &MockStorage_DeleteRole_Call{Call: _e.mock.On("DeleteRole", id)}
}

func (_c *MockStorage_DeleteRole_Call) Run(run func(id string)) *MockStorage_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteRole_Call) Return(_a0 error) *MockStorage_DeleteRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteRole_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoleAssignment provides a mock function with given fields: id
func (_m *MockStorage) DeleteRoleAssignment(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoleAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteRoleAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoleAssignment'
type MockStorage_DeleteRoleAssignment_Call struct {
	*mock.Call
}

// DeleteRoleAssignment is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteRoleAssignment(id interface{}) *MockStorage_DeleteRoleAssignment_Call {
	return &MockStorage_DeleteRoleAssignment_Call{Call: _e.mock.On("DeleteRoleAssignment", id)}
}

func (_c *MockStorage_DeleteRoleAssignment_Call) Run(run func(id string)) *MockStorage_DeleteRoleAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteRoleAssignment_Call) Return(_a0 error) *MockStorage_DeleteRoleAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteRoleAssignment_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteRoleAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserProfile provides a mock function with given fields: id
func (_m *MockStorage) DeleteUserProfile(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserProfile'
type MockStorage_DeleteUserProfile_Call struct {
	*mock.Call
}

// DeleteUserProfile is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteUserProfile(id interface{}) *MockStorage_DeleteUserProfile_Call {
	return &MockStorage_DeleteUserProfile_Call{Call: _e.mock.On("DeleteUserProfile", id)}
}

func (_c *MockStorage_DeleteUserProfile_Call) Run(run func(id string)) *MockStorage_DeleteUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteUserProfile_Call) Return(_a0 error) *MockStorage_DeleteUserProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteUserProfile_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function with given fields: id
func (_m *MockStorage) DeleteWorkspace(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type MockStorage_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) DeleteWorkspace(id interface{}) *MockStorage_DeleteWorkspace_Call {
	return &MockStorage_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", id)}
}

func (_c *MockStorage_DeleteWorkspace_Call) Run(run func(id string)) *MockStorage_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteWorkspace_Call) Return(_a0 error) *MockStorage_DeleteWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteWorkspace_Call) RunAndReturn(run func(string) error) *MockStorage_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GenericQuery provides a mock function with given fields: table, selectFields, filters, result
func (_m *MockStorage) GenericQuery(table string, selectFields string, filters []storage.Filter, result interface{}) error {
	ret := _m.Called(table, selectFields, filters, result)

	if len(ret) == 0 {
		panic("no return value specified for GenericQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []storage.Filter, interface{}) error); ok {
		r0 = rf(table, selectFields, filters, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_GenericQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenericQuery'
type MockStorage_GenericQuery_Call struct {
	*mock.Call
}

// GenericQuery is a helper method to define mock.On call
//   - table string
//   - selectFields string
//   - filters []storage.Filter
//   - result interface{}
func (_e *MockStorage_Expecter) GenericQuery(table interface{}, selectFields interface{}, filters interface{}, result interface{}) *MockStorage_GenericQuery_Call {
	return &MockStorage_GenericQuery_Call{Call: _e.mock.On("GenericQuery", table, selectFields, filters, result)}
}

func (_c *MockStorage_GenericQuery_Call) Run(run func(table string, selectFields string, filters []storage.Filter, result interface{})) *MockStorage_GenericQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]storage.Filter), args[3].(interface{}))
	})
	return _c
}

func (_c *MockStorage_GenericQuery_Call) Return(_a0 error) *MockStorage_GenericQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GenericQuery_Call) RunAndReturn(run func(string, string, []storage.Filter, interface{}) error) *MockStorage_GenericQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiKey provides a mock function with given fields: id
func (_m *MockStorage) GetApiKey(id string) (*v1.ApiKey, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApiKey")
	}

	var r0 *v1.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.ApiKey, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.ApiKey); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiKey'
type MockStorage_GetApiKey_Call struct {
	*mock.Call
}

// GetApiKey is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetApiKey(id interface{}) *MockStorage_GetApiKey_Call {
	return &MockStorage_GetApiKey_Call{Call: _e.mock.On("GetApiKey", id)}
}

func (_c *MockStorage_GetApiKey_Call) Run(run func(id string)) *MockStorage_GetApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetApiKey_Call) Return(_a0 *v1.ApiKey, _a1 error) *MockStorage_GetApiKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetApiKey_Call) RunAndReturn(run func(string) (*v1.ApiKey, error)) *MockStorage_GetApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function with given fields: id
func (_m *MockStorage) GetCluster(id string) (*v1.Cluster, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *v1.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.Cluster, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.Cluster); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type MockStorage_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetCluster(id interface{}) *MockStorage_GetCluster_Call {
	return &MockStorage_GetCluster_Call{Call: _e.mock.On("GetCluster", id)}
}

func (_c *MockStorage_GetCluster_Call) Run(run func(id string)) *MockStorage_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetCluster_Call) Return(_a0 *v1.Cluster, _a1 error) *MockStorage_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetCluster_Call) RunAndReturn(run func(string) (*v1.Cluster, error)) *MockStorage_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpoint provides a mock function with given fields: id
func (_m *MockStorage) GetEndpoint(id string) (*v1.Endpoint, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 *v1.Endpoint
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.Endpoint, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.Endpoint); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Endpoint)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type MockStorage_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetEndpoint(id interface{}) *MockStorage_GetEndpoint_Call {
	return &MockStorage_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint", id)}
}

func (_c *MockStorage_GetEndpoint_Call) Run(run func(id string)) *MockStorage_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetEndpoint_Call) Return(_a0 *v1.Endpoint, _a1 error) *MockStorage_GetEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetEndpoint_Call) RunAndReturn(run func(string) (*v1.Endpoint, error)) *MockStorage_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetEngine provides a mock function with given fields: id
func (_m *MockStorage) GetEngine(id string) (*v1.Engine, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEngine")
	}

	var r0 *v1.Engine
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.Engine, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.Engine); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Engine)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEngine'
type MockStorage_GetEngine_Call struct {
	*mock.Call
}

// GetEngine is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetEngine(id interface{}) *MockStorage_GetEngine_Call {
	return &MockStorage_GetEngine_Call{Call: _e.mock.On("GetEngine", id)}
}

func (_c *MockStorage_GetEngine_Call) Run(run func(id string)) *MockStorage_GetEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetEngine_Call) Return(_a0 *v1.Engine, _a1 error) *MockStorage_GetEngine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetEngine_Call) RunAndReturn(run func(string) (*v1.Engine, error)) *MockStorage_GetEngine_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageRegistry provides a mock function with given fields: id
func (_m *MockStorage) GetImageRegistry(id string) (*v1.ImageRegistry, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetImageRegistry")
	}

	var r0 *v1.ImageRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.ImageRegistry, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.ImageRegistry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ImageRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageRegistry'
type MockStorage_GetImageRegistry_Call struct {
	*mock.Call
}

// GetImageRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetImageRegistry(id interface{}) *MockStorage_GetImageRegistry_Call {
	return &MockStorage_GetImageRegistry_Call{Call: _e.mock.On("GetImageRegistry", id)}
}

func (_c *MockStorage_GetImageRegistry_Call) Run(run func(id string)) *MockStorage_GetImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetImageRegistry_Call) Return(_a0 *v1.ImageRegistry, _a1 error) *MockStorage_GetImageRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetImageRegistry_Call) RunAndReturn(run func(string) (*v1.ImageRegistry, error)) *MockStorage_GetImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelCatalog provides a mock function with given fields: id
func (_m *MockStorage) GetModelCatalog(id string) (*v1.ModelCatalog, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetModelCatalog")
	}

	var r0 *v1.ModelCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.ModelCatalog, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.ModelCatalog); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ModelCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetModelCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelCatalog'
type MockStorage_GetModelCatalog_Call struct {
	*mock.Call
}

// GetModelCatalog is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetModelCatalog(id interface{}) *MockStorage_GetModelCatalog_Call {
	return &MockStorage_GetModelCatalog_Call{Call: _e.mock.On("GetModelCatalog", id)}
}

func (_c *MockStorage_GetModelCatalog_Call) Run(run func(id string)) *MockStorage_GetModelCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetModelCatalog_Call) Return(_a0 *v1.ModelCatalog, _a1 error) *MockStorage_GetModelCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetModelCatalog_Call) RunAndReturn(run func(string) (*v1.ModelCatalog, error)) *MockStorage_GetModelCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelRegistry provides a mock function with given fields: id
func (_m *MockStorage) GetModelRegistry(id string) (*v1.ModelRegistry, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetModelRegistry")
	}

	var r0 *v1.ModelRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.ModelRegistry, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.ModelRegistry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ModelRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelRegistry'
type MockStorage_GetModelRegistry_Call struct {
	*mock.Call
}

// GetModelRegistry is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetModelRegistry(id interface{}) *MockStorage_GetModelRegistry_Call {
	return &MockStorage_GetModelRegistry_Call{Call: _e.mock.On("GetModelRegistry", id)}
}

func (_c *MockStorage_GetModelRegistry_Call) Run(run func(id string)) *MockStorage_GetModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetModelRegistry_Call) Return(_a0 *v1.ModelRegistry, _a1 error) *MockStorage_GetModelRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetModelRegistry_Call) RunAndReturn(run func(string) (*v1.ModelRegistry, error)) *MockStorage_GetModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: id
func (_m *MockStorage) GetRole(id string) (*v1.Role, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *v1.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.Role, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.Role); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type MockStorage_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetRole(id interface{}) *MockStorage_GetRole_Call {
	return &MockStorage_GetRole_Call{Call: _e.mock.On("GetRole", id)}
}

func (_c *MockStorage_GetRole_Call) Run(run func(id string)) *MockStorage_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetRole_Call) Return(_a0 *v1.Role, _a1 error) *MockStorage_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetRole_Call) RunAndReturn(run func(string) (*v1.Role, error)) *MockStorage_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignment provides a mock function with given fields: id
func (_m *MockStorage) GetRoleAssignment(id string) (*v1.RoleAssignment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignment")
	}

	var r0 *v1.RoleAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.RoleAssignment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.RoleAssignment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RoleAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetRoleAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignment'
type MockStorage_GetRoleAssignment_Call struct {
	*mock.Call
}

// GetRoleAssignment is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetRoleAssignment(id interface{}) *MockStorage_GetRoleAssignment_Call {
	return &MockStorage_GetRoleAssignment_Call{Call: _e.mock.On("GetRoleAssignment", id)}
}

func (_c *MockStorage_GetRoleAssignment_Call) Run(run func(id string)) *MockStorage_GetRoleAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetRoleAssignment_Call) Return(_a0 *v1.RoleAssignment, _a1 error) *MockStorage_GetRoleAssignment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetRoleAssignment_Call) RunAndReturn(run func(string) (*v1.RoleAssignment, error)) *MockStorage_GetRoleAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfile provides a mock function with given fields: id
func (_m *MockStorage) GetUserProfile(id string) (*v1.UserProfile, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *v1.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.UserProfile, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.UserProfile); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type MockStorage_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetUserProfile(id interface{}) *MockStorage_GetUserProfile_Call {
	return &MockStorage_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", id)}
}

func (_c *MockStorage_GetUserProfile_Call) Run(run func(id string)) *MockStorage_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetUserProfile_Call) Return(_a0 *v1.UserProfile, _a1 error) *MockStorage_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetUserProfile_Call) RunAndReturn(run func(string) (*v1.UserProfile, error)) *MockStorage_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function with given fields: id
func (_m *MockStorage) GetWorkspace(id string) (*v1.Workspace, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 *v1.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.Workspace, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.Workspace); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockStorage_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - id string
func (_e *MockStorage_Expecter) GetWorkspace(id interface{}) *MockStorage_GetWorkspace_Call {
	return &MockStorage_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", id)}
}

func (_c *MockStorage_GetWorkspace_Call) Run(run func(id string)) *MockStorage_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_GetWorkspace_Call) Return(_a0 *v1.Workspace, _a1 error) *MockStorage_GetWorkspace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetWorkspace_Call) RunAndReturn(run func(string) (*v1.Workspace, error)) *MockStorage_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListApiKey provides a mock function with given fields: option
func (_m *MockStorage) ListApiKey(option storage.ListOption) ([]v1.ApiKey, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListApiKey")
	}

	var r0 []v1.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ApiKey, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ApiKey); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApiKey'
type MockStorage_ListApiKey_Call struct {
	*mock.Call
}

// ListApiKey is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListApiKey(option interface{}) *MockStorage_ListApiKey_Call {
	return &MockStorage_ListApiKey_Call{Call: _e.mock.On("ListApiKey", option)}
}

func (_c *MockStorage_ListApiKey_Call) Run(run func(option storage.ListOption)) *MockStorage_ListApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListApiKey_Call) Return(_a0 []v1.ApiKey, _a1 error) *MockStorage_ListApiKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListApiKey_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ApiKey, error)) *MockStorage_ListApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListCluster provides a mock function with given fields: option
func (_m *MockStorage) ListCluster(option storage.ListOption) ([]v1.Cluster, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListCluster")
	}

	var r0 []v1.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.Cluster, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.Cluster); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCluster'
type MockStorage_ListCluster_Call struct {
	*mock.Call
}

// ListCluster is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListCluster(option interface{}) *MockStorage_ListCluster_Call {
	return &MockStorage_ListCluster_Call{Call: _e.mock.On("ListCluster", option)}
}

func (_c *MockStorage_ListCluster_Call) Run(run func(option storage.ListOption)) *MockStorage_ListCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListCluster_Call) Return(_a0 []v1.Cluster, _a1 error) *MockStorage_ListCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListCluster_Call) RunAndReturn(run func(storage.ListOption) ([]v1.Cluster, error)) *MockStorage_ListCluster_Call {
	_c.Call.Return(run)
	return _c
}

// ListEndpoint provides a mock function with given fields: option
func (_m *MockStorage) ListEndpoint(option storage.ListOption) ([]v1.Endpoint, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListEndpoint")
	}

	var r0 []v1.Endpoint
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.Endpoint, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.Endpoint); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Endpoint)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEndpoint'
type MockStorage_ListEndpoint_Call struct {
	*mock.Call
}

// ListEndpoint is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListEndpoint(option interface{}) *MockStorage_ListEndpoint_Call {
	return &MockStorage_ListEndpoint_Call{Call: _e.mock.On("ListEndpoint", option)}
}

func (_c *MockStorage_ListEndpoint_Call) Run(run func(option storage.ListOption)) *MockStorage_ListEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListEndpoint_Call) Return(_a0 []v1.Endpoint, _a1 error) *MockStorage_ListEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListEndpoint_Call) RunAndReturn(run func(storage.ListOption) ([]v1.Endpoint, error)) *MockStorage_ListEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// ListEngine provides a mock function with given fields: option
func (_m *MockStorage) ListEngine(option storage.ListOption) ([]v1.Engine, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListEngine")
	}

	var r0 []v1.Engine
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.Engine, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.Engine); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Engine)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEngine'
type MockStorage_ListEngine_Call struct {
	*mock.Call
}

// ListEngine is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListEngine(option interface{}) *MockStorage_ListEngine_Call {
	return &MockStorage_ListEngine_Call{Call: _e.mock.On("ListEngine", option)}
}

func (_c *MockStorage_ListEngine_Call) Run(run func(option storage.ListOption)) *MockStorage_ListEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListEngine_Call) Return(_a0 []v1.Engine, _a1 error) *MockStorage_ListEngine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListEngine_Call) RunAndReturn(run func(storage.ListOption) ([]v1.Engine, error)) *MockStorage_ListEngine_Call {
	_c.Call.Return(run)
	return _c
}

// ListImageRegistry provides a mock function with given fields: option
func (_m *MockStorage) ListImageRegistry(option storage.ListOption) ([]v1.ImageRegistry, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListImageRegistry")
	}

	var r0 []v1.ImageRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ImageRegistry, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ImageRegistry); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ImageRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImageRegistry'
type MockStorage_ListImageRegistry_Call struct {
	*mock.Call
}

// ListImageRegistry is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListImageRegistry(option interface{}) *MockStorage_ListImageRegistry_Call {
	return &MockStorage_ListImageRegistry_Call{Call: _e.mock.On("ListImageRegistry", option)}
}

func (_c *MockStorage_ListImageRegistry_Call) Run(run func(option storage.ListOption)) *MockStorage_ListImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListImageRegistry_Call) Return(_a0 []v1.ImageRegistry, _a1 error) *MockStorage_ListImageRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListImageRegistry_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ImageRegistry, error)) *MockStorage_ListImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// ListModelCatalog provides a mock function with given fields: option
func (_m *MockStorage) ListModelCatalog(option storage.ListOption) ([]v1.ModelCatalog, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListModelCatalog")
	}

	var r0 []v1.ModelCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ModelCatalog, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ModelCatalog); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ModelCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListModelCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModelCatalog'
type MockStorage_ListModelCatalog_Call struct {
	*mock.Call
}

// ListModelCatalog is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListModelCatalog(option interface{}) *MockStorage_ListModelCatalog_Call {
	return &MockStorage_ListModelCatalog_Call{Call: _e.mock.On("ListModelCatalog", option)}
}

func (_c *MockStorage_ListModelCatalog_Call) Run(run func(option storage.ListOption)) *MockStorage_ListModelCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListModelCatalog_Call) Return(_a0 []v1.ModelCatalog, _a1 error) *MockStorage_ListModelCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListModelCatalog_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ModelCatalog, error)) *MockStorage_ListModelCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// ListModelRegistry provides a mock function with given fields: option
func (_m *MockStorage) ListModelRegistry(option storage.ListOption) ([]v1.ModelRegistry, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListModelRegistry")
	}

	var r0 []v1.ModelRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.ModelRegistry, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.ModelRegistry); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ModelRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModelRegistry'
type MockStorage_ListModelRegistry_Call struct {
	*mock.Call
}

// ListModelRegistry is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListModelRegistry(option interface{}) *MockStorage_ListModelRegistry_Call {
	return &MockStorage_ListModelRegistry_Call{Call: _e.mock.On("ListModelRegistry", option)}
}

func (_c *MockStorage_ListModelRegistry_Call) Run(run func(option storage.ListOption)) *MockStorage_ListModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListModelRegistry_Call) Return(_a0 []v1.ModelRegistry, _a1 error) *MockStorage_ListModelRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListModelRegistry_Call) RunAndReturn(run func(storage.ListOption) ([]v1.ModelRegistry, error)) *MockStorage_ListModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// ListRole provides a mock function with given fields: option
func (_m *MockStorage) ListRole(option storage.ListOption) ([]v1.Role, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListRole")
	}

	var r0 []v1.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.Role, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.Role); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRole'
type MockStorage_ListRole_Call struct {
	*mock.Call
}

// ListRole is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListRole(option interface{}) *MockStorage_ListRole_Call {
	return &MockStorage_ListRole_Call{Call: _e.mock.On("ListRole", option)}
}

func (_c *MockStorage_ListRole_Call) Run(run func(option storage.ListOption)) *MockStorage_ListRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListRole_Call) Return(_a0 []v1.Role, _a1 error) *MockStorage_ListRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListRole_Call) RunAndReturn(run func(storage.ListOption) ([]v1.Role, error)) *MockStorage_ListRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoleAssignment provides a mock function with given fields: option
func (_m *MockStorage) ListRoleAssignment(option storage.ListOption) ([]v1.RoleAssignment, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListRoleAssignment")
	}

	var r0 []v1.RoleAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.RoleAssignment, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.RoleAssignment); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.RoleAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListRoleAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoleAssignment'
type MockStorage_ListRoleAssignment_Call struct {
	*mock.Call
}

// ListRoleAssignment is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListRoleAssignment(option interface{}) *MockStorage_ListRoleAssignment_Call {
	return &MockStorage_ListRoleAssignment_Call{Call: _e.mock.On("ListRoleAssignment", option)}
}

func (_c *MockStorage_ListRoleAssignment_Call) Run(run func(option storage.ListOption)) *MockStorage_ListRoleAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListRoleAssignment_Call) Return(_a0 []v1.RoleAssignment, _a1 error) *MockStorage_ListRoleAssignment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListRoleAssignment_Call) RunAndReturn(run func(storage.ListOption) ([]v1.RoleAssignment, error)) *MockStorage_ListRoleAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserProfile provides a mock function with given fields: option
func (_m *MockStorage) ListUserProfile(option storage.ListOption) ([]v1.UserProfile, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListUserProfile")
	}

	var r0 []v1.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.UserProfile, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.UserProfile); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserProfile'
type MockStorage_ListUserProfile_Call struct {
	*mock.Call
}

// ListUserProfile is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListUserProfile(option interface{}) *MockStorage_ListUserProfile_Call {
	return &MockStorage_ListUserProfile_Call{Call: _e.mock.On("ListUserProfile", option)}
}

func (_c *MockStorage_ListUserProfile_Call) Run(run func(option storage.ListOption)) *MockStorage_ListUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListUserProfile_Call) Return(_a0 []v1.UserProfile, _a1 error) *MockStorage_ListUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListUserProfile_Call) RunAndReturn(run func(storage.ListOption) ([]v1.UserProfile, error)) *MockStorage_ListUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspace provides a mock function with given fields: option
func (_m *MockStorage) ListWorkspace(option storage.ListOption) ([]v1.Workspace, error) {
	ret := _m.Called(option)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspace")
	}

	var r0 []v1.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.ListOption) ([]v1.Workspace, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(storage.ListOption) []v1.Workspace); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.ListOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspace'
type MockStorage_ListWorkspace_Call struct {
	*mock.Call
}

// ListWorkspace is a helper method to define mock.On call
//   - option storage.ListOption
func (_e *MockStorage_Expecter) ListWorkspace(option interface{}) *MockStorage_ListWorkspace_Call {
	return &MockStorage_ListWorkspace_Call{Call: _e.mock.On("ListWorkspace", option)}
}

func (_c *MockStorage_ListWorkspace_Call) Run(run func(option storage.ListOption)) *MockStorage_ListWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.ListOption))
	})
	return _c
}

func (_c *MockStorage_ListWorkspace_Call) Return(_a0 []v1.Workspace, _a1 error) *MockStorage_ListWorkspace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListWorkspace_Call) RunAndReturn(run func(storage.ListOption) ([]v1.Workspace, error)) *MockStorage_ListWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApiKey provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateApiKey(id string, data *v1.ApiKey) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApiKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ApiKey) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApiKey'
type MockStorage_UpdateApiKey_Call struct {
	*mock.Call
}

// UpdateApiKey is a helper method to define mock.On call
//   - id string
//   - data *v1.ApiKey
func (_e *MockStorage_Expecter) UpdateApiKey(id interface{}, data interface{}) *MockStorage_UpdateApiKey_Call {
	return &MockStorage_UpdateApiKey_Call{Call: _e.mock.On("UpdateApiKey", id, data)}
}

func (_c *MockStorage_UpdateApiKey_Call) Run(run func(id string, data *v1.ApiKey)) *MockStorage_UpdateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ApiKey))
	})
	return _c
}

func (_c *MockStorage_UpdateApiKey_Call) Return(_a0 error) *MockStorage_UpdateApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateApiKey_Call) RunAndReturn(run func(string, *v1.ApiKey) error) *MockStorage_UpdateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCluster provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateCluster(id string, data *v1.Cluster) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.Cluster) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCluster'
type MockStorage_UpdateCluster_Call struct {
	*mock.Call
}

// UpdateCluster is a helper method to define mock.On call
//   - id string
//   - data *v1.Cluster
func (_e *MockStorage_Expecter) UpdateCluster(id interface{}, data interface{}) *MockStorage_UpdateCluster_Call {
	return &MockStorage_UpdateCluster_Call{Call: _e.mock.On("UpdateCluster", id, data)}
}

func (_c *MockStorage_UpdateCluster_Call) Run(run func(id string, data *v1.Cluster)) *MockStorage_UpdateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.Cluster))
	})
	return _c
}

func (_c *MockStorage_UpdateCluster_Call) Return(_a0 error) *MockStorage_UpdateCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateCluster_Call) RunAndReturn(run func(string, *v1.Cluster) error) *MockStorage_UpdateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEndpoint provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateEndpoint(id string, data *v1.Endpoint) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.Endpoint) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEndpoint'
type MockStorage_UpdateEndpoint_Call struct {
	*mock.Call
}

// UpdateEndpoint is a helper method to define mock.On call
//   - id string
//   - data *v1.Endpoint
func (_e *MockStorage_Expecter) UpdateEndpoint(id interface{}, data interface{}) *MockStorage_UpdateEndpoint_Call {
	return &MockStorage_UpdateEndpoint_Call{Call: _e.mock.On("UpdateEndpoint", id, data)}
}

func (_c *MockStorage_UpdateEndpoint_Call) Run(run func(id string, data *v1.Endpoint)) *MockStorage_UpdateEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.Endpoint))
	})
	return _c
}

func (_c *MockStorage_UpdateEndpoint_Call) Return(_a0 error) *MockStorage_UpdateEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateEndpoint_Call) RunAndReturn(run func(string, *v1.Endpoint) error) *MockStorage_UpdateEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEngine provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateEngine(id string, data *v1.Engine) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEngine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.Engine) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEngine'
type MockStorage_UpdateEngine_Call struct {
	*mock.Call
}

// UpdateEngine is a helper method to define mock.On call
//   - id string
//   - data *v1.Engine
func (_e *MockStorage_Expecter) UpdateEngine(id interface{}, data interface{}) *MockStorage_UpdateEngine_Call {
	return &MockStorage_UpdateEngine_Call{Call: _e.mock.On("UpdateEngine", id, data)}
}

func (_c *MockStorage_UpdateEngine_Call) Run(run func(id string, data *v1.Engine)) *MockStorage_UpdateEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.Engine))
	})
	return _c
}

func (_c *MockStorage_UpdateEngine_Call) Return(_a0 error) *MockStorage_UpdateEngine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateEngine_Call) RunAndReturn(run func(string, *v1.Engine) error) *MockStorage_UpdateEngine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImageRegistry provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateImageRegistry(id string, data *v1.ImageRegistry) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImageRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ImageRegistry) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateImageRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImageRegistry'
type MockStorage_UpdateImageRegistry_Call struct {
	*mock.Call
}

// UpdateImageRegistry is a helper method to define mock.On call
//   - id string
//   - data *v1.ImageRegistry
func (_e *MockStorage_Expecter) UpdateImageRegistry(id interface{}, data interface{}) *MockStorage_UpdateImageRegistry_Call {
	return &MockStorage_UpdateImageRegistry_Call{Call: _e.mock.On("UpdateImageRegistry", id, data)}
}

func (_c *MockStorage_UpdateImageRegistry_Call) Run(run func(id string, data *v1.ImageRegistry)) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ImageRegistry))
	})
	return _c
}

func (_c *MockStorage_UpdateImageRegistry_Call) Return(_a0 error) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateImageRegistry_Call) RunAndReturn(run func(string, *v1.ImageRegistry) error) *MockStorage_UpdateImageRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateModelCatalog provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateModelCatalog(id string, data *v1.ModelCatalog) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateModelCatalog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ModelCatalog) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateModelCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateModelCatalog'
type MockStorage_UpdateModelCatalog_Call struct {
	*mock.Call
}

// UpdateModelCatalog is a helper method to define mock.On call
//   - id string
//   - data *v1.ModelCatalog
func (_e *MockStorage_Expecter) UpdateModelCatalog(id interface{}, data interface{}) *MockStorage_UpdateModelCatalog_Call {
	return &MockStorage_UpdateModelCatalog_Call{Call: _e.mock.On("UpdateModelCatalog", id, data)}
}

func (_c *MockStorage_UpdateModelCatalog_Call) Run(run func(id string, data *v1.ModelCatalog)) *MockStorage_UpdateModelCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ModelCatalog))
	})
	return _c
}

func (_c *MockStorage_UpdateModelCatalog_Call) Return(_a0 error) *MockStorage_UpdateModelCatalog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateModelCatalog_Call) RunAndReturn(run func(string, *v1.ModelCatalog) error) *MockStorage_UpdateModelCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateModelRegistry provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateModelRegistry(id string, data *v1.ModelRegistry) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateModelRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.ModelRegistry) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateModelRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateModelRegistry'
type MockStorage_UpdateModelRegistry_Call struct {
	*mock.Call
}

// UpdateModelRegistry is a helper method to define mock.On call
//   - id string
//   - data *v1.ModelRegistry
func (_e *MockStorage_Expecter) UpdateModelRegistry(id interface{}, data interface{}) *MockStorage_UpdateModelRegistry_Call {
	return &MockStorage_UpdateModelRegistry_Call{Call: _e.mock.On("UpdateModelRegistry", id, data)}
}

func (_c *MockStorage_UpdateModelRegistry_Call) Run(run func(id string, data *v1.ModelRegistry)) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.ModelRegistry))
	})
	return _c
}

func (_c *MockStorage_UpdateModelRegistry_Call) Return(_a0 error) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateModelRegistry_Call) RunAndReturn(run func(string, *v1.ModelRegistry) error) *MockStorage_UpdateModelRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateRole(id string, data *v1.Role) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.Role) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockStorage_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - id string
//   - data *v1.Role
func (_e *MockStorage_Expecter) UpdateRole(id interface{}, data interface{}) *MockStorage_UpdateRole_Call {
	return &MockStorage_UpdateRole_Call{Call: _e.mock.On("UpdateRole", id, data)}
}

func (_c *MockStorage_UpdateRole_Call) Run(run func(id string, data *v1.Role)) *MockStorage_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.Role))
	})
	return _c
}

func (_c *MockStorage_UpdateRole_Call) Return(_a0 error) *MockStorage_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateRole_Call) RunAndReturn(run func(string, *v1.Role) error) *MockStorage_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoleAssignment provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateRoleAssignment(id string, data *v1.RoleAssignment) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoleAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RoleAssignment) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateRoleAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoleAssignment'
type MockStorage_UpdateRoleAssignment_Call struct {
	*mock.Call
}

// UpdateRoleAssignment is a helper method to define mock.On call
//   - id string
//   - data *v1.RoleAssignment
func (_e *MockStorage_Expecter) UpdateRoleAssignment(id interface{}, data interface{}) *MockStorage_UpdateRoleAssignment_Call {
	return &MockStorage_UpdateRoleAssignment_Call{Call: _e.mock.On("UpdateRoleAssignment", id, data)}
}

func (_c *MockStorage_UpdateRoleAssignment_Call) Run(run func(id string, data *v1.RoleAssignment)) *MockStorage_UpdateRoleAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.RoleAssignment))
	})
	return _c
}

func (_c *MockStorage_UpdateRoleAssignment_Call) Return(_a0 error) *MockStorage_UpdateRoleAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateRoleAssignment_Call) RunAndReturn(run func(string, *v1.RoleAssignment) error) *MockStorage_UpdateRoleAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateUserProfile(id string, data *v1.UserProfile) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.UserProfile) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockStorage_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - id string
//   - data *v1.UserProfile
func (_e *MockStorage_Expecter) UpdateUserProfile(id interface{}, data interface{}) *MockStorage_UpdateUserProfile_Call {
	return &MockStorage_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", id, data)}
}

func (_c *MockStorage_UpdateUserProfile_Call) Run(run func(id string, data *v1.UserProfile)) *MockStorage_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.UserProfile))
	})
	return _c
}

func (_c *MockStorage_UpdateUserProfile_Call) Return(_a0 error) *MockStorage_UpdateUserProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateUserProfile_Call) RunAndReturn(run func(string, *v1.UserProfile) error) *MockStorage_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspace provides a mock function with given fields: id, data
func (_m *MockStorage) UpdateWorkspace(id string, data *v1.Workspace) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.Workspace) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspace'
type MockStorage_UpdateWorkspace_Call struct {
	*mock.Call
}

// UpdateWorkspace is a helper method to define mock.On call
//   - id string
//   - data *v1.Workspace
func (_e *MockStorage_Expecter) UpdateWorkspace(id interface{}, data interface{}) *MockStorage_UpdateWorkspace_Call {
	return &MockStorage_UpdateWorkspace_Call{Call: _e.mock.On("UpdateWorkspace", id, data)}
}

func (_c *MockStorage_UpdateWorkspace_Call) Run(run func(id string, data *v1.Workspace)) *MockStorage_UpdateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.Workspace))
	})
	return _c
}

func (_c *MockStorage_UpdateWorkspace_Call) Return(_a0 error) *MockStorage_UpdateWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateWorkspace_Call) RunAndReturn(run func(string, *v1.Workspace) error) *MockStorage_UpdateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
