// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	plugin "github.com/neutree-ai/neutree/internal/accelerator/plugin"
	mock "github.com/stretchr/testify/mock"

	resourceparser "github.com/neutree-ai/neutree/internal/accelerator/resourceparser"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// DetectAccelerator provides a mock function with given fields: ctx, runner
func (_m *MockManager) DetectAccelerator(ctx context.Context, runner plugin.NodeCommandRunner) (*v1.StaticNodeAcceleratorStatus, error) {
	ret := _m.Called(ctx, runner)

	if len(ret) == 0 {
		panic("no return value specified for DetectAccelerator")
	}

	var r0 *v1.StaticNodeAcceleratorStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plugin.NodeCommandRunner) (*v1.StaticNodeAcceleratorStatus, error)); ok {
		return rf(ctx, runner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plugin.NodeCommandRunner) *v1.StaticNodeAcceleratorStatus); ok {
		r0 = rf(ctx, runner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.StaticNodeAcceleratorStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, plugin.NodeCommandRunner) error); ok {
		r1 = rf(ctx, runner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_DetectAccelerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectAccelerator'
type MockManager_DetectAccelerator_Call struct {
	*mock.Call
}

// DetectAccelerator is a helper method to define mock.On call
//   - ctx context.Context
//   - runner plugin.NodeCommandRunner
func (_e *MockManager_Expecter) DetectAccelerator(ctx interface{}, runner interface{}) *MockManager_DetectAccelerator_Call {
	return &MockManager_DetectAccelerator_Call{Call: _e.mock.On("DetectAccelerator", ctx, runner)}
}

func (_c *MockManager_DetectAccelerator_Call) Run(run func(ctx context.Context, runner plugin.NodeCommandRunner)) *MockManager_DetectAccelerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plugin.NodeCommandRunner))
	})
	return _c
}

func (_c *MockManager_DetectAccelerator_Call) Return(_a0 *v1.StaticNodeAcceleratorStatus, _a1 error) *MockManager_DetectAccelerator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_DetectAccelerator_Call) RunAndReturn(run func(context.Context, plugin.NodeCommandRunner) (*v1.StaticNodeAcceleratorStatus, error)) *MockManager_DetectAccelerator_Call {
	_c.Call.Return(run)
	return _c
}

// GetAcceleratorProfile provides a mock function with given fields: ctx, acceleratorType
func (_m *MockManager) GetAcceleratorProfile(ctx context.Context, acceleratorType string) (*v1.AcceleratorProfile, bool, error) {
	ret := _m.Called(ctx, acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetAcceleratorProfile")
	}

	var r0 *v1.AcceleratorProfile
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1.AcceleratorProfile, bool, error)); ok {
		return rf(ctx, acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.AcceleratorProfile); ok {
		r0 = rf(ctx, acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AcceleratorProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, acceleratorType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockManager_GetAcceleratorProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAcceleratorProfile'
type MockManager_GetAcceleratorProfile_Call struct {
	*mock.Call
}

// GetAcceleratorProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - acceleratorType string
func (_e *MockManager_Expecter) GetAcceleratorProfile(ctx interface{}, acceleratorType interface{}) *MockManager_GetAcceleratorProfile_Call {
	return &MockManager_GetAcceleratorProfile_Call{Call: _e.mock.On("GetAcceleratorProfile", ctx, acceleratorType)}
}

func (_c *MockManager_GetAcceleratorProfile_Call) Run(run func(ctx context.Context, acceleratorType string)) *MockManager_GetAcceleratorProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_GetAcceleratorProfile_Call) Return(_a0 *v1.AcceleratorProfile, _a1 bool, _a2 error) *MockManager_GetAcceleratorProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockManager_GetAcceleratorProfile_Call) RunAndReturn(run func(context.Context, string) (*v1.AcceleratorProfile, bool, error)) *MockManager_GetAcceleratorProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllConverters provides a mock function with no fields
func (_m *MockManager) GetAllConverters() map[string]plugin.ResourceConverter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllConverters")
	}

	var r0 map[string]plugin.ResourceConverter
	if rf, ok := ret.Get(0).(func() map[string]plugin.ResourceConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]plugin.ResourceConverter)
		}
	}

	return r0
}

// MockManager_GetAllConverters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConverters'
type MockManager_GetAllConverters_Call struct {
	*mock.Call
}

// GetAllConverters is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAllConverters() *MockManager_GetAllConverters_Call {
	return &MockManager_GetAllConverters_Call{Call: _e.mock.On("GetAllConverters")}
}

func (_c *MockManager_GetAllConverters_Call) Run(run func()) *MockManager_GetAllConverters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAllConverters_Call) Return(_a0 map[string]plugin.ResourceConverter) *MockManager_GetAllConverters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetAllConverters_Call) RunAndReturn(run func() map[string]plugin.ResourceConverter) *MockManager_GetAllConverters_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllParsers provides a mock function with no fields
func (_m *MockManager) GetAllParsers() map[string]resourceparser.ResourceParser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllParsers")
	}

	var r0 map[string]resourceparser.ResourceParser
	if rf, ok := ret.Get(0).(func() map[string]resourceparser.ResourceParser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]resourceparser.ResourceParser)
		}
	}

	return r0
}

// MockManager_GetAllParsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllParsers'
type MockManager_GetAllParsers_Call struct {
	*mock.Call
}

// GetAllParsers is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAllParsers() *MockManager_GetAllParsers_Call {
	return &MockManager_GetAllParsers_Call{Call: _e.mock.On("GetAllParsers")}
}

func (_c *MockManager_GetAllParsers_Call) Run(run func()) *MockManager_GetAllParsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAllParsers_Call) Return(_a0 map[string]resourceparser.ResourceParser) *MockManager_GetAllParsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetAllParsers_Call) RunAndReturn(run func() map[string]resourceparser.ResourceParser) *MockManager_GetAllParsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetConverter provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetConverter(acceleratorType string) (plugin.ResourceConverter, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetConverter")
	}

	var r0 plugin.ResourceConverter
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (plugin.ResourceConverter, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) plugin.ResourceConverter); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ResourceConverter)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockManager_GetConverter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConverter'
type MockManager_GetConverter_Call struct {
	*mock.Call
}

// GetConverter is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetConverter(acceleratorType interface{}) *MockManager_GetConverter_Call {
	return &MockManager_GetConverter_Call{Call: _e.mock.On("GetConverter", acceleratorType)}
}

func (_c *MockManager_GetConverter_Call) Run(run func(acceleratorType string)) *MockManager_GetConverter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetConverter_Call) Return(_a0 plugin.ResourceConverter, _a1 bool) *MockManager_GetConverter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetConverter_Call) RunAndReturn(run func(string) (plugin.ResourceConverter, bool)) *MockManager_GetConverter_Call {
	_c.Call.Return(run)
	return _c
}

// GetEngineContainerRunOptions provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetEngineContainerRunOptions(acceleratorType string) ([]string, error) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetEngineContainerRunOptions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetEngineContainerRunOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEngineContainerRunOptions'
type MockManager_GetEngineContainerRunOptions_Call struct {
	*mock.Call
}

// GetEngineContainerRunOptions is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetEngineContainerRunOptions(acceleratorType interface{}) *MockManager_GetEngineContainerRunOptions_Call {
	return &MockManager_GetEngineContainerRunOptions_Call{Call: _e.mock.On("GetEngineContainerRunOptions", acceleratorType)}
}

func (_c *MockManager_GetEngineContainerRunOptions_Call) Run(run func(acceleratorType string)) *MockManager_GetEngineContainerRunOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetEngineContainerRunOptions_Call) Return(_a0 []string, _a1 error) *MockManager_GetEngineContainerRunOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetEngineContainerRunOptions_Call) RunAndReturn(run func(string) ([]string, error)) *MockManager_GetEngineContainerRunOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageSuffix provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetImageSuffix(acceleratorType string) string {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetImageSuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(acceleratorType)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockManager_GetImageSuffix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageSuffix'
type MockManager_GetImageSuffix_Call struct {
	*mock.Call
}

// GetImageSuffix is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetImageSuffix(acceleratorType interface{}) *MockManager_GetImageSuffix_Call {
	return &MockManager_GetImageSuffix_Call{Call: _e.mock.On("GetImageSuffix", acceleratorType)}
}

func (_c *MockManager_GetImageSuffix_Call) Run(run func(acceleratorType string)) *MockManager_GetImageSuffix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetImageSuffix_Call) Return(_a0 string) *MockManager_GetImageSuffix_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetImageSuffix_Call) RunAndReturn(run func(string) string) *MockManager_GetImageSuffix_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeAcceleratorType provides a mock function with given fields: ctx, nodeIp, sshAuth
func (_m *MockManager) GetNodeAcceleratorType(ctx context.Context, nodeIp string, sshAuth v1.Auth) (string, error) {
	ret := _m.Called(ctx, nodeIp, sshAuth)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeAcceleratorType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.Auth) (string, error)); ok {
		return rf(ctx, nodeIp, sshAuth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.Auth) string); ok {
		r0 = rf(ctx, nodeIp, sshAuth)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.Auth) error); ok {
		r1 = rf(ctx, nodeIp, sshAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetNodeAcceleratorType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeAcceleratorType'
type MockManager_GetNodeAcceleratorType_Call struct {
	*mock.Call
}

// GetNodeAcceleratorType is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeIp string
//   - sshAuth v1.Auth
func (_e *MockManager_Expecter) GetNodeAcceleratorType(ctx interface{}, nodeIp interface{}, sshAuth interface{}) *MockManager_GetNodeAcceleratorType_Call {
	return &MockManager_GetNodeAcceleratorType_Call{Call: _e.mock.On("GetNodeAcceleratorType", ctx, nodeIp, sshAuth)}
}

func (_c *MockManager_GetNodeAcceleratorType_Call) Run(run func(ctx context.Context, nodeIp string, sshAuth v1.Auth)) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.Auth))
	})
	return _c
}

func (_c *MockManager_GetNodeAcceleratorType_Call) Return(_a0 string, _a1 error) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetNodeAcceleratorType_Call) RunAndReturn(run func(context.Context, string, v1.Auth) (string, error)) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeRuntimeConfig provides a mock function with given fields: ctx, acceleratorType, nodeIp, sshAuth
func (_m *MockManager) GetNodeRuntimeConfig(ctx context.Context, acceleratorType string, nodeIp string, sshAuth v1.Auth) (v1.RuntimeConfig, error) {
	ret := _m.Called(ctx, acceleratorType, nodeIp, sshAuth)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeRuntimeConfig")
	}

	var r0 v1.RuntimeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1.Auth) (v1.RuntimeConfig, error)); ok {
		return rf(ctx, acceleratorType, nodeIp, sshAuth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1.Auth) v1.RuntimeConfig); ok {
		r0 = rf(ctx, acceleratorType, nodeIp, sshAuth)
	} else {
		r0 = ret.Get(0).(v1.RuntimeConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, v1.Auth) error); ok {
		r1 = rf(ctx, acceleratorType, nodeIp, sshAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetNodeRuntimeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeRuntimeConfig'
type MockManager_GetNodeRuntimeConfig_Call struct {
	*mock.Call
}

// GetNodeRuntimeConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - acceleratorType string
//   - nodeIp string
//   - sshAuth v1.Auth
func (_e *MockManager_Expecter) GetNodeRuntimeConfig(ctx interface{}, acceleratorType interface{}, nodeIp interface{}, sshAuth interface{}) *MockManager_GetNodeRuntimeConfig_Call {
	return &MockManager_GetNodeRuntimeConfig_Call{Call: _e.mock.On("GetNodeRuntimeConfig", ctx, acceleratorType, nodeIp, sshAuth)}
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) Run(run func(ctx context.Context, acceleratorType string, nodeIp string, sshAuth v1.Auth)) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(v1.Auth))
	})
	return _c
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) Return(_a0 v1.RuntimeConfig, _a1 error) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) RunAndReturn(run func(context.Context, string, string, v1.Auth) (v1.RuntimeConfig, error)) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetParser provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetParser(acceleratorType string) (resourceparser.ResourceParser, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetParser")
	}

	var r0 resourceparser.ResourceParser
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (resourceparser.ResourceParser, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) resourceparser.ResourceParser); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resourceparser.ResourceParser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockManager_GetParser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParser'
type MockManager_GetParser_Call struct {
	*mock.Call
}

// GetParser is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetParser(acceleratorType interface{}) *MockManager_GetParser_Call {
	return &MockManager_GetParser_Call{Call: _e.mock.On("GetParser", acceleratorType)}
}

func (_c *MockManager_GetParser_Call) Run(run func(acceleratorType string)) *MockManager_GetParser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetParser_Call) Return(_a0 resourceparser.ResourceParser, _a1 bool) *MockManager_GetParser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetParser_Call) RunAndReturn(run func(string) (resourceparser.ResourceParser, bool)) *MockManager_GetParser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlugin provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetPlugin(acceleratorType string) (plugin.AcceleratorPlugin, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetPlugin")
	}

	var r0 plugin.AcceleratorPlugin
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (plugin.AcceleratorPlugin, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) plugin.AcceleratorPlugin); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.AcceleratorPlugin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockManager_GetPlugin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlugin'
type MockManager_GetPlugin_Call struct {
	*mock.Call
}

// GetPlugin is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetPlugin(acceleratorType interface{}) *MockManager_GetPlugin_Call {
	return &MockManager_GetPlugin_Call{Call: _e.mock.On("GetPlugin", acceleratorType)}
}

func (_c *MockManager_GetPlugin_Call) Run(run func(acceleratorType string)) *MockManager_GetPlugin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetPlugin_Call) Return(_a0 plugin.AcceleratorPlugin, _a1 bool) *MockManager_GetPlugin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetPlugin_Call) RunAndReturn(run func(string) (plugin.AcceleratorPlugin, bool)) *MockManager_GetPlugin_Call {
	_c.Call.Return(run)
	return _c
}

// RuntimeProfile provides a mock function with given fields: ctx, _a1
func (_m *MockManager) RuntimeProfile(ctx context.Context, _a1 v1.StaticNodeAcceleratorStatus) (*v1.AcceleratorProfile, bool, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RuntimeProfile")
	}

	var r0 *v1.AcceleratorProfile
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.StaticNodeAcceleratorStatus) (*v1.AcceleratorProfile, bool, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.StaticNodeAcceleratorStatus) *v1.AcceleratorProfile); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AcceleratorProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.StaticNodeAcceleratorStatus) bool); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, v1.StaticNodeAcceleratorStatus) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockManager_RuntimeProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RuntimeProfile'
type MockManager_RuntimeProfile_Call struct {
	*mock.Call
}

// RuntimeProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 v1.StaticNodeAcceleratorStatus
func (_e *MockManager_Expecter) RuntimeProfile(ctx interface{}, _a1 interface{}) *MockManager_RuntimeProfile_Call {
	return &MockManager_RuntimeProfile_Call{Call: _e.mock.On("RuntimeProfile", ctx, _a1)}
}

func (_c *MockManager_RuntimeProfile_Call) Run(run func(ctx context.Context, _a1 v1.StaticNodeAcceleratorStatus)) *MockManager_RuntimeProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.StaticNodeAcceleratorStatus))
	})
	return _c
}

func (_c *MockManager_RuntimeProfile_Call) Return(_a0 *v1.AcceleratorProfile, _a1 bool, _a2 error) *MockManager_RuntimeProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockManager_RuntimeProfile_Call) RunAndReturn(run func(context.Context, v1.StaticNodeAcceleratorStatus) (*v1.AcceleratorProfile, bool, error)) *MockManager_RuntimeProfile_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockManager) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Start(ctx interface{}) *MockManager_Start_Call {
	return &MockManager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockManager_Start_Call) Run(run func(ctx context.Context)) *MockManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_Start_Call) Return() *MockManager_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Start_Call) RunAndReturn(run func(context.Context)) *MockManager_Start_Call {
	_c.Run(run)
	return _c
}

// SupportPlugins provides a mock function with no fields
func (_m *MockManager) SupportPlugins() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportPlugins")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockManager_SupportPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportPlugins'
type MockManager_SupportPlugins_Call struct {
	*mock.Call
}

// SupportPlugins is a helper method to define mock.On call
func (_e *MockManager_Expecter) SupportPlugins() *MockManager_SupportPlugins_Call {
	return &MockManager_SupportPlugins_Call{Call: _e.mock.On("SupportPlugins")}
}

func (_c *MockManager_SupportPlugins_Call) Run(run func()) *MockManager_SupportPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_SupportPlugins_Call) Return(_a0 []string) *MockManager_SupportPlugins_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_SupportPlugins_Call) RunAndReturn(run func() []string) *MockManager_SupportPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
