// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	plugin "github.com/neutree-ai/neutree/internal/accelerator/plugin"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GetAllAcceleratorSupportEngines provides a mock function with given fields: ctx
func (_m *MockManager) GetAllAcceleratorSupportEngines(ctx context.Context) ([]*v1.Engine, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAcceleratorSupportEngines")
	}

	var r0 []*v1.Engine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*v1.Engine, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*v1.Engine); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Engine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetAllAcceleratorSupportEngines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAcceleratorSupportEngines'
type MockManager_GetAllAcceleratorSupportEngines_Call struct {
	*mock.Call
}

// GetAllAcceleratorSupportEngines is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) GetAllAcceleratorSupportEngines(ctx interface{}) *MockManager_GetAllAcceleratorSupportEngines_Call {
	return &MockManager_GetAllAcceleratorSupportEngines_Call{Call: _e.mock.On("GetAllAcceleratorSupportEngines", ctx)}
}

func (_c *MockManager_GetAllAcceleratorSupportEngines_Call) Run(run func(ctx context.Context)) *MockManager_GetAllAcceleratorSupportEngines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_GetAllAcceleratorSupportEngines_Call) Return(_a0 []*v1.Engine, _a1 error) *MockManager_GetAllAcceleratorSupportEngines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetAllAcceleratorSupportEngines_Call) RunAndReturn(run func(context.Context) ([]*v1.Engine, error)) *MockManager_GetAllAcceleratorSupportEngines_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllConverters provides a mock function with no fields
func (_m *MockManager) GetAllConverters() map[string]plugin.ResourceConverter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllConverters")
	}

	var r0 map[string]plugin.ResourceConverter
	if rf, ok := ret.Get(0).(func() map[string]plugin.ResourceConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]plugin.ResourceConverter)
		}
	}

	return r0
}

// MockManager_GetAllConverters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConverters'
type MockManager_GetAllConverters_Call struct {
	*mock.Call
}

// GetAllConverters is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAllConverters() *MockManager_GetAllConverters_Call {
	return &MockManager_GetAllConverters_Call{Call: _e.mock.On("GetAllConverters")}
}

func (_c *MockManager_GetAllConverters_Call) Run(run func()) *MockManager_GetAllConverters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAllConverters_Call) Return(_a0 map[string]plugin.ResourceConverter) *MockManager_GetAllConverters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetAllConverters_Call) RunAndReturn(run func() map[string]plugin.ResourceConverter) *MockManager_GetAllConverters_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllParsers provides a mock function with no fields
func (_m *MockManager) GetAllParsers() map[string]plugin.ResourceParser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllParsers")
	}

	var r0 map[string]plugin.ResourceParser
	if rf, ok := ret.Get(0).(func() map[string]plugin.ResourceParser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]plugin.ResourceParser)
		}
	}

	return r0
}

// MockManager_GetAllParsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllParsers'
type MockManager_GetAllParsers_Call struct {
	*mock.Call
}

// GetAllParsers is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetAllParsers() *MockManager_GetAllParsers_Call {
	return &MockManager_GetAllParsers_Call{Call: _e.mock.On("GetAllParsers")}
}

func (_c *MockManager_GetAllParsers_Call) Run(run func()) *MockManager_GetAllParsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetAllParsers_Call) Return(_a0 map[string]plugin.ResourceParser) *MockManager_GetAllParsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetAllParsers_Call) RunAndReturn(run func() map[string]plugin.ResourceParser) *MockManager_GetAllParsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetConverter provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetConverter(acceleratorType string) (plugin.ResourceConverter, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetConverter")
	}

	var r0 plugin.ResourceConverter
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (plugin.ResourceConverter, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) plugin.ResourceConverter); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ResourceConverter)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockManager_GetConverter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConverter'
type MockManager_GetConverter_Call struct {
	*mock.Call
}

// GetConverter is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetConverter(acceleratorType interface{}) *MockManager_GetConverter_Call {
	return &MockManager_GetConverter_Call{Call: _e.mock.On("GetConverter", acceleratorType)}
}

func (_c *MockManager_GetConverter_Call) Run(run func(acceleratorType string)) *MockManager_GetConverter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetConverter_Call) Return(_a0 plugin.ResourceConverter, _a1 bool) *MockManager_GetConverter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetConverter_Call) RunAndReturn(run func(string) (plugin.ResourceConverter, bool)) *MockManager_GetConverter_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeAcceleratorType provides a mock function with given fields: ctx, nodeIp, sshAuth
func (_m *MockManager) GetNodeAcceleratorType(ctx context.Context, nodeIp string, sshAuth v1.Auth) (string, error) {
	ret := _m.Called(ctx, nodeIp, sshAuth)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeAcceleratorType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.Auth) (string, error)); ok {
		return rf(ctx, nodeIp, sshAuth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.Auth) string); ok {
		r0 = rf(ctx, nodeIp, sshAuth)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.Auth) error); ok {
		r1 = rf(ctx, nodeIp, sshAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetNodeAcceleratorType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeAcceleratorType'
type MockManager_GetNodeAcceleratorType_Call struct {
	*mock.Call
}

// GetNodeAcceleratorType is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeIp string
//   - sshAuth v1.Auth
func (_e *MockManager_Expecter) GetNodeAcceleratorType(ctx interface{}, nodeIp interface{}, sshAuth interface{}) *MockManager_GetNodeAcceleratorType_Call {
	return &MockManager_GetNodeAcceleratorType_Call{Call: _e.mock.On("GetNodeAcceleratorType", ctx, nodeIp, sshAuth)}
}

func (_c *MockManager_GetNodeAcceleratorType_Call) Run(run func(ctx context.Context, nodeIp string, sshAuth v1.Auth)) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.Auth))
	})
	return _c
}

func (_c *MockManager_GetNodeAcceleratorType_Call) Return(_a0 string, _a1 error) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetNodeAcceleratorType_Call) RunAndReturn(run func(context.Context, string, v1.Auth) (string, error)) *MockManager_GetNodeAcceleratorType_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeRuntimeConfig provides a mock function with given fields: ctx, acceleratorType, nodeIp, sshAuth
func (_m *MockManager) GetNodeRuntimeConfig(ctx context.Context, acceleratorType string, nodeIp string, sshAuth v1.Auth) (v1.RuntimeConfig, error) {
	ret := _m.Called(ctx, acceleratorType, nodeIp, sshAuth)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeRuntimeConfig")
	}

	var r0 v1.RuntimeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1.Auth) (v1.RuntimeConfig, error)); ok {
		return rf(ctx, acceleratorType, nodeIp, sshAuth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1.Auth) v1.RuntimeConfig); ok {
		r0 = rf(ctx, acceleratorType, nodeIp, sshAuth)
	} else {
		r0 = ret.Get(0).(v1.RuntimeConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, v1.Auth) error); ok {
		r1 = rf(ctx, acceleratorType, nodeIp, sshAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetNodeRuntimeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeRuntimeConfig'
type MockManager_GetNodeRuntimeConfig_Call struct {
	*mock.Call
}

// GetNodeRuntimeConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - acceleratorType string
//   - nodeIp string
//   - sshAuth v1.Auth
func (_e *MockManager_Expecter) GetNodeRuntimeConfig(ctx interface{}, acceleratorType interface{}, nodeIp interface{}, sshAuth interface{}) *MockManager_GetNodeRuntimeConfig_Call {
	return &MockManager_GetNodeRuntimeConfig_Call{Call: _e.mock.On("GetNodeRuntimeConfig", ctx, acceleratorType, nodeIp, sshAuth)}
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) Run(run func(ctx context.Context, acceleratorType string, nodeIp string, sshAuth v1.Auth)) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(v1.Auth))
	})
	return _c
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) Return(_a0 v1.RuntimeConfig, _a1 error) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetNodeRuntimeConfig_Call) RunAndReturn(run func(context.Context, string, string, v1.Auth) (v1.RuntimeConfig, error)) *MockManager_GetNodeRuntimeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetParser provides a mock function with given fields: acceleratorType
func (_m *MockManager) GetParser(acceleratorType string) (plugin.ResourceParser, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetParser")
	}

	var r0 plugin.ResourceParser
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (plugin.ResourceParser, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) plugin.ResourceParser); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ResourceParser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockManager_GetParser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParser'
type MockManager_GetParser_Call struct {
	*mock.Call
}

// GetParser is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockManager_Expecter) GetParser(acceleratorType interface{}) *MockManager_GetParser_Call {
	return &MockManager_GetParser_Call{Call: _e.mock.On("GetParser", acceleratorType)}
}

func (_c *MockManager_GetParser_Call) Run(run func(acceleratorType string)) *MockManager_GetParser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetParser_Call) Return(_a0 plugin.ResourceParser, _a1 bool) *MockManager_GetParser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetParser_Call) RunAndReturn(run func(string) (plugin.ResourceParser, bool)) *MockManager_GetParser_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockManager) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Start(ctx interface{}) *MockManager_Start_Call {
	return &MockManager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockManager_Start_Call) Run(run func(ctx context.Context)) *MockManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_Start_Call) Return() *MockManager_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Start_Call) RunAndReturn(run func(context.Context)) *MockManager_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
