// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	v1 "github.com/neutree-ai/neutree/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockPluginRegistry is an autogenerated mock type for the PluginRegistry type
type MockPluginRegistry struct {
	mock.Mock
}

type MockPluginRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginRegistry) EXPECT() *MockPluginRegistry_Expecter {
	return &MockPluginRegistry_Expecter{mock: &_m.Mock}
}

// GetAllConverters provides a mock function with no fields
func (_m *MockPluginRegistry) GetAllConverters() map[string]v1.ResourceConverter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllConverters")
	}

	var r0 map[string]v1.ResourceConverter
	if rf, ok := ret.Get(0).(func() map[string]v1.ResourceConverter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]v1.ResourceConverter)
		}
	}

	return r0
}

// MockPluginRegistry_GetAllConverters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConverters'
type MockPluginRegistry_GetAllConverters_Call struct {
	*mock.Call
}

// GetAllConverters is a helper method to define mock.On call
func (_e *MockPluginRegistry_Expecter) GetAllConverters() *MockPluginRegistry_GetAllConverters_Call {
	return &MockPluginRegistry_GetAllConverters_Call{Call: _e.mock.On("GetAllConverters")}
}

func (_c *MockPluginRegistry_GetAllConverters_Call) Run(run func()) *MockPluginRegistry_GetAllConverters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginRegistry_GetAllConverters_Call) Return(_a0 map[string]v1.ResourceConverter) *MockPluginRegistry_GetAllConverters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPluginRegistry_GetAllConverters_Call) RunAndReturn(run func() map[string]v1.ResourceConverter) *MockPluginRegistry_GetAllConverters_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllParsers provides a mock function with no fields
func (_m *MockPluginRegistry) GetAllParsers() map[string]v1.ResourceParser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllParsers")
	}

	var r0 map[string]v1.ResourceParser
	if rf, ok := ret.Get(0).(func() map[string]v1.ResourceParser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]v1.ResourceParser)
		}
	}

	return r0
}

// MockPluginRegistry_GetAllParsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllParsers'
type MockPluginRegistry_GetAllParsers_Call struct {
	*mock.Call
}

// GetAllParsers is a helper method to define mock.On call
func (_e *MockPluginRegistry_Expecter) GetAllParsers() *MockPluginRegistry_GetAllParsers_Call {
	return &MockPluginRegistry_GetAllParsers_Call{Call: _e.mock.On("GetAllParsers")}
}

func (_c *MockPluginRegistry_GetAllParsers_Call) Run(run func()) *MockPluginRegistry_GetAllParsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginRegistry_GetAllParsers_Call) Return(_a0 map[string]v1.ResourceParser) *MockPluginRegistry_GetAllParsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPluginRegistry_GetAllParsers_Call) RunAndReturn(run func() map[string]v1.ResourceParser) *MockPluginRegistry_GetAllParsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetConverter provides a mock function with given fields: acceleratorType
func (_m *MockPluginRegistry) GetConverter(acceleratorType string) (v1.ResourceConverter, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetConverter")
	}

	var r0 v1.ResourceConverter
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (v1.ResourceConverter, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) v1.ResourceConverter); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ResourceConverter)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPluginRegistry_GetConverter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConverter'
type MockPluginRegistry_GetConverter_Call struct {
	*mock.Call
}

// GetConverter is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockPluginRegistry_Expecter) GetConverter(acceleratorType interface{}) *MockPluginRegistry_GetConverter_Call {
	return &MockPluginRegistry_GetConverter_Call{Call: _e.mock.On("GetConverter", acceleratorType)}
}

func (_c *MockPluginRegistry_GetConverter_Call) Run(run func(acceleratorType string)) *MockPluginRegistry_GetConverter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPluginRegistry_GetConverter_Call) Return(_a0 v1.ResourceConverter, _a1 bool) *MockPluginRegistry_GetConverter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPluginRegistry_GetConverter_Call) RunAndReturn(run func(string) (v1.ResourceConverter, bool)) *MockPluginRegistry_GetConverter_Call {
	_c.Call.Return(run)
	return _c
}

// GetParser provides a mock function with given fields: acceleratorType
func (_m *MockPluginRegistry) GetParser(acceleratorType string) (v1.ResourceParser, bool) {
	ret := _m.Called(acceleratorType)

	if len(ret) == 0 {
		panic("no return value specified for GetParser")
	}

	var r0 v1.ResourceParser
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (v1.ResourceParser, bool)); ok {
		return rf(acceleratorType)
	}
	if rf, ok := ret.Get(0).(func(string) v1.ResourceParser); ok {
		r0 = rf(acceleratorType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ResourceParser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(acceleratorType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPluginRegistry_GetParser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParser'
type MockPluginRegistry_GetParser_Call struct {
	*mock.Call
}

// GetParser is a helper method to define mock.On call
//   - acceleratorType string
func (_e *MockPluginRegistry_Expecter) GetParser(acceleratorType interface{}) *MockPluginRegistry_GetParser_Call {
	return &MockPluginRegistry_GetParser_Call{Call: _e.mock.On("GetParser", acceleratorType)}
}

func (_c *MockPluginRegistry_GetParser_Call) Run(run func(acceleratorType string)) *MockPluginRegistry_GetParser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPluginRegistry_GetParser_Call) Return(_a0 v1.ResourceParser, _a1 bool) *MockPluginRegistry_GetParser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPluginRegistry_GetParser_Call) RunAndReturn(run func(string) (v1.ResourceParser, bool)) *MockPluginRegistry_GetParser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPluginRegistry creates a new instance of MockPluginRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginRegistry {
	mock := &MockPluginRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
