// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator struct {
	mock.Mock
}

type MockOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator) EXPECT() *MockOrchestrator_Expecter {
	return &MockOrchestrator_Expecter{mock: &_m.Mock}
}

// ClusterStatus provides a mock function with no fields
func (_m *MockOrchestrator) ClusterStatus() (*v1.RayClusterStatus, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterStatus")
	}

	var r0 *v1.RayClusterStatus
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v1.RayClusterStatus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v1.RayClusterStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RayClusterStatus)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_ClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterStatus'
type MockOrchestrator_ClusterStatus_Call struct {
	*mock.Call
}

// ClusterStatus is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) ClusterStatus() *MockOrchestrator_ClusterStatus_Call {
	return &MockOrchestrator_ClusterStatus_Call{Call: _e.mock.On("ClusterStatus")}
}

func (_c *MockOrchestrator_ClusterStatus_Call) Run(run func()) *MockOrchestrator_ClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_ClusterStatus_Call) Return(_a0 *v1.RayClusterStatus, _a1 error) *MockOrchestrator_ClusterStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_ClusterStatus_Call) RunAndReturn(run func() (*v1.RayClusterStatus, error)) *MockOrchestrator_ClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCluster provides a mock function with no fields
func (_m *MockOrchestrator) CreateCluster() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type MockOrchestrator_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) CreateCluster() *MockOrchestrator_CreateCluster_Call {
	return &MockOrchestrator_CreateCluster_Call{Call: _e.mock.On("CreateCluster")}
}

func (_c *MockOrchestrator_CreateCluster_Call) Run(run func()) *MockOrchestrator_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_CreateCluster_Call) Return(_a0 string, _a1 error) *MockOrchestrator_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_CreateCluster_Call) RunAndReturn(run func() (string, error)) *MockOrchestrator_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEndpoint provides a mock function with given fields: endpoint
func (_m *MockOrchestrator) CreateEndpoint(endpoint *v1.Endpoint) (*v1.EndpointStatus, error) {
	ret := _m.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for CreateEndpoint")
	}

	var r0 *v1.EndpointStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) (*v1.EndpointStatus, error)); ok {
		return rf(endpoint)
	}
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) *v1.EndpointStatus); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.EndpointStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.Endpoint) error); ok {
		r1 = rf(endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_CreateEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEndpoint'
type MockOrchestrator_CreateEndpoint_Call struct {
	*mock.Call
}

// CreateEndpoint is a helper method to define mock.On call
//   - endpoint *v1.Endpoint
func (_e *MockOrchestrator_Expecter) CreateEndpoint(endpoint interface{}) *MockOrchestrator_CreateEndpoint_Call {
	return &MockOrchestrator_CreateEndpoint_Call{Call: _e.mock.On("CreateEndpoint", endpoint)}
}

func (_c *MockOrchestrator_CreateEndpoint_Call) Run(run func(endpoint *v1.Endpoint)) *MockOrchestrator_CreateEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Endpoint))
	})
	return _c
}

func (_c *MockOrchestrator_CreateEndpoint_Call) Return(_a0 *v1.EndpointStatus, _a1 error) *MockOrchestrator_CreateEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_CreateEndpoint_Call) RunAndReturn(run func(*v1.Endpoint) (*v1.EndpointStatus, error)) *MockOrchestrator_CreateEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function with no fields
func (_m *MockOrchestrator) DeleteCluster() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type MockOrchestrator_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) DeleteCluster() *MockOrchestrator_DeleteCluster_Call {
	return &MockOrchestrator_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster")}
}

func (_c *MockOrchestrator_DeleteCluster_Call) Run(run func()) *MockOrchestrator_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_DeleteCluster_Call) Return(_a0 error) *MockOrchestrator_DeleteCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_DeleteCluster_Call) RunAndReturn(run func() error) *MockOrchestrator_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEndpoint provides a mock function with given fields: endpoint
func (_m *MockOrchestrator) DeleteEndpoint(endpoint *v1.Endpoint) error {
	ret := _m.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) error); ok {
		r0 = rf(endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_DeleteEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEndpoint'
type MockOrchestrator_DeleteEndpoint_Call struct {
	*mock.Call
}

// DeleteEndpoint is a helper method to define mock.On call
//   - endpoint *v1.Endpoint
func (_e *MockOrchestrator_Expecter) DeleteEndpoint(endpoint interface{}) *MockOrchestrator_DeleteEndpoint_Call {
	return &MockOrchestrator_DeleteEndpoint_Call{Call: _e.mock.On("DeleteEndpoint", endpoint)}
}

func (_c *MockOrchestrator_DeleteEndpoint_Call) Run(run func(endpoint *v1.Endpoint)) *MockOrchestrator_DeleteEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Endpoint))
	})
	return _c
}

func (_c *MockOrchestrator_DeleteEndpoint_Call) Return(_a0 error) *MockOrchestrator_DeleteEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_DeleteEndpoint_Call) RunAndReturn(run func(*v1.Endpoint) error) *MockOrchestrator_DeleteEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetDesireStaticWorkersIP provides a mock function with no fields
func (_m *MockOrchestrator) GetDesireStaticWorkersIP() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDesireStaticWorkersIP")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockOrchestrator_GetDesireStaticWorkersIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDesireStaticWorkersIP'
type MockOrchestrator_GetDesireStaticWorkersIP_Call struct {
	*mock.Call
}

// GetDesireStaticWorkersIP is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) GetDesireStaticWorkersIP() *MockOrchestrator_GetDesireStaticWorkersIP_Call {
	return &MockOrchestrator_GetDesireStaticWorkersIP_Call{Call: _e.mock.On("GetDesireStaticWorkersIP")}
}

func (_c *MockOrchestrator_GetDesireStaticWorkersIP_Call) Run(run func()) *MockOrchestrator_GetDesireStaticWorkersIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_GetDesireStaticWorkersIP_Call) Return(_a0 []string) *MockOrchestrator_GetDesireStaticWorkersIP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_GetDesireStaticWorkersIP_Call) RunAndReturn(run func() []string) *MockOrchestrator_GetDesireStaticWorkersIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpointStatus provides a mock function with given fields: endpoint
func (_m *MockOrchestrator) GetEndpointStatus(endpoint *v1.Endpoint) (*v1.EndpointStatus, error) {
	ret := _m.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointStatus")
	}

	var r0 *v1.EndpointStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) (*v1.EndpointStatus, error)); ok {
		return rf(endpoint)
	}
	if rf, ok := ret.Get(0).(func(*v1.Endpoint) *v1.EndpointStatus); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.EndpointStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.Endpoint) error); ok {
		r1 = rf(endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_GetEndpointStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpointStatus'
type MockOrchestrator_GetEndpointStatus_Call struct {
	*mock.Call
}

// GetEndpointStatus is a helper method to define mock.On call
//   - endpoint *v1.Endpoint
func (_e *MockOrchestrator_Expecter) GetEndpointStatus(endpoint interface{}) *MockOrchestrator_GetEndpointStatus_Call {
	return &MockOrchestrator_GetEndpointStatus_Call{Call: _e.mock.On("GetEndpointStatus", endpoint)}
}

func (_c *MockOrchestrator_GetEndpointStatus_Call) Run(run func(endpoint *v1.Endpoint)) *MockOrchestrator_GetEndpointStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Endpoint))
	})
	return _c
}

func (_c *MockOrchestrator_GetEndpointStatus_Call) Return(_a0 *v1.EndpointStatus, _a1 error) *MockOrchestrator_GetEndpointStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_GetEndpointStatus_Call) RunAndReturn(run func(*v1.Endpoint) (*v1.EndpointStatus, error)) *MockOrchestrator_GetEndpointStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with no fields
func (_m *MockOrchestrator) HealthCheck() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockOrchestrator_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) HealthCheck() *MockOrchestrator_HealthCheck_Call {
	return &MockOrchestrator_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockOrchestrator_HealthCheck_Call) Run(run func()) *MockOrchestrator_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_HealthCheck_Call) Return(_a0 error) *MockOrchestrator_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_HealthCheck_Call) RunAndReturn(run func() error) *MockOrchestrator_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodes provides a mock function with no fields
func (_m *MockOrchestrator) ListNodes() ([]v1.NodeSummary, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []v1.NodeSummary
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]v1.NodeSummary, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []v1.NodeSummary); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.NodeSummary)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type MockOrchestrator_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) ListNodes() *MockOrchestrator_ListNodes_Call {
	return &MockOrchestrator_ListNodes_Call{Call: _e.mock.On("ListNodes")}
}

func (_c *MockOrchestrator_ListNodes_Call) Run(run func()) *MockOrchestrator_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_ListNodes_Call) Return(_a0 []v1.NodeSummary, _a1 error) *MockOrchestrator_ListNodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_ListNodes_Call) RunAndReturn(run func() ([]v1.NodeSummary, error)) *MockOrchestrator_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// StartNode provides a mock function with given fields: nodeIP
func (_m *MockOrchestrator) StartNode(nodeIP string) error {
	ret := _m.Called(nodeIP)

	if len(ret) == 0 {
		panic("no return value specified for StartNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(nodeIP)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_StartNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNode'
type MockOrchestrator_StartNode_Call struct {
	*mock.Call
}

// StartNode is a helper method to define mock.On call
//   - nodeIP string
func (_e *MockOrchestrator_Expecter) StartNode(nodeIP interface{}) *MockOrchestrator_StartNode_Call {
	return &MockOrchestrator_StartNode_Call{Call: _e.mock.On("StartNode", nodeIP)}
}

func (_c *MockOrchestrator_StartNode_Call) Run(run func(nodeIP string)) *MockOrchestrator_StartNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrchestrator_StartNode_Call) Return(_a0 error) *MockOrchestrator_StartNode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_StartNode_Call) RunAndReturn(run func(string) error) *MockOrchestrator_StartNode_Call {
	_c.Call.Return(run)
	return _c
}

// StopNode provides a mock function with given fields: nodeIP
func (_m *MockOrchestrator) StopNode(nodeIP string) error {
	ret := _m.Called(nodeIP)

	if len(ret) == 0 {
		panic("no return value specified for StopNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(nodeIP)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_StopNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopNode'
type MockOrchestrator_StopNode_Call struct {
	*mock.Call
}

// StopNode is a helper method to define mock.On call
//   - nodeIP string
func (_e *MockOrchestrator_Expecter) StopNode(nodeIP interface{}) *MockOrchestrator_StopNode_Call {
	return &MockOrchestrator_StopNode_Call{Call: _e.mock.On("StopNode", nodeIP)}
}

func (_c *MockOrchestrator_StopNode_Call) Run(run func(nodeIP string)) *MockOrchestrator_StopNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrchestrator_StopNode_Call) Return(_a0 error) *MockOrchestrator_StopNode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_StopNode_Call) RunAndReturn(run func(string) error) *MockOrchestrator_StopNode_Call {
	_c.Call.Return(run)
	return _c
}

// SyncCluster provides a mock function with no fields
func (_m *MockOrchestrator) SyncCluster() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_SyncCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncCluster'
type MockOrchestrator_SyncCluster_Call struct {
	*mock.Call
}

// SyncCluster is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter) SyncCluster() *MockOrchestrator_SyncCluster_Call {
	return &MockOrchestrator_SyncCluster_Call{Call: _e.mock.On("SyncCluster")}
}

func (_c *MockOrchestrator_SyncCluster_Call) Run(run func()) *MockOrchestrator_SyncCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_SyncCluster_Call) Return(_a0 error) *MockOrchestrator_SyncCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_SyncCluster_Call) RunAndReturn(run func() error) *MockOrchestrator_SyncCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator {
	mock := &MockOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
