// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	io "io"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/neutree-ai/neutree/api/v1"
)

// MockK8sClient is an autogenerated mock type for the K8sClient type
type MockK8sClient struct {
	mock.Mock
}

type MockK8sClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK8sClient) EXPECT() *MockK8sClient_Expecter {
	return &MockK8sClient_Expecter{mock: &_m.Mock}
}

// GetPod provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockK8sClient) GetPod(ctx context.Context, cluster *v1.Cluster, namespace string, name string) (*corev1.Pod, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPod")
	}

	var r0 *corev1.Pod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster, string, string) (*corev1.Pod, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster, string, string) *corev1.Pod); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Pod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Cluster, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockK8sClient_GetPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPod'
type MockK8sClient_GetPod_Call struct {
	*mock.Call
}

// GetPod is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster *v1.Cluster
//   - namespace string
//   - name string
func (_e *MockK8sClient_Expecter) GetPod(ctx interface{}, cluster interface{}, namespace interface{}, name interface{}) *MockK8sClient_GetPod_Call {
	return &MockK8sClient_GetPod_Call{Call: _e.mock.On("GetPod", ctx, cluster, namespace, name)}
}

func (_c *MockK8sClient_GetPod_Call) Run(run func(ctx context.Context, cluster *v1.Cluster, namespace string, name string)) *MockK8sClient_GetPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Cluster), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockK8sClient_GetPod_Call) Return(_a0 *corev1.Pod, _a1 error) *MockK8sClient_GetPod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockK8sClient_GetPod_Call) RunAndReturn(run func(context.Context, *v1.Cluster, string, string) (*corev1.Pod, error)) *MockK8sClient_GetPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodLogs provides a mock function with given fields: ctx, cluster, namespace, podName, opts
func (_m *MockK8sClient) GetPodLogs(ctx context.Context, cluster *v1.Cluster, namespace string, podName string, opts *corev1.PodLogOptions) (io.ReadCloser, error) {
	ret := _m.Called(ctx, cluster, namespace, podName, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetPodLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster, string, string, *corev1.PodLogOptions) (io.ReadCloser, error)); ok {
		return rf(ctx, cluster, namespace, podName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster, string, string, *corev1.PodLogOptions) io.ReadCloser); ok {
		r0 = rf(ctx, cluster, namespace, podName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Cluster, string, string, *corev1.PodLogOptions) error); ok {
		r1 = rf(ctx, cluster, namespace, podName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockK8sClient_GetPodLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodLogs'
type MockK8sClient_GetPodLogs_Call struct {
	*mock.Call
}

// GetPodLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster *v1.Cluster
//   - namespace string
//   - podName string
//   - opts *corev1.PodLogOptions
func (_e *MockK8sClient_Expecter) GetPodLogs(ctx interface{}, cluster interface{}, namespace interface{}, podName interface{}, opts interface{}) *MockK8sClient_GetPodLogs_Call {
	return &MockK8sClient_GetPodLogs_Call{Call: _e.mock.On("GetPodLogs", ctx, cluster, namespace, podName, opts)}
}

func (_c *MockK8sClient_GetPodLogs_Call) Run(run func(ctx context.Context, cluster *v1.Cluster, namespace string, podName string, opts *corev1.PodLogOptions)) *MockK8sClient_GetPodLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Cluster), args[2].(string), args[3].(string), args[4].(*corev1.PodLogOptions))
	})
	return _c
}

func (_c *MockK8sClient_GetPodLogs_Call) Return(_a0 io.ReadCloser, _a1 error) *MockK8sClient_GetPodLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockK8sClient_GetPodLogs_Call) RunAndReturn(run func(context.Context, *v1.Cluster, string, string, *corev1.PodLogOptions) (io.ReadCloser, error)) *MockK8sClient_GetPodLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK8sClient creates a new instance of MockK8sClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK8sClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK8sClient {
	mock := &MockK8sClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
