apiVersion: v1
kind: Service
metadata:
  namespace: {{  .Release.Namespace }}
  name: {{ include "neutree.fullname" . }}-auth-service
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: neutree-auth