apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "gateway/kong/plugins/neutree-observability/*").AsConfig | indent 2 }}
metadata:
  labels:
    app.kubernetes.io/component: kong-plugin
  name: neutree-observability
