apiVersion: v1
kind: Service
metadata:
  name: {{ include "neutree.fullname" . }}-plugin-server-service
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.pluginServer.service.type | default "ClusterIP" }}
  ports:
    - port: 3001
      targetPort: plugin-server
      protocol: TCP
      name: plugin-server
  selector:
    app.kubernetes.io/component: neutree-core
