apiVersion: v1
kind: Service
metadata:
  name: {{ include "neutree.fullname" . }}-server-service
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.server.service.type | default "ClusterIP" }}
  ports:
    - port: 3001
      targetPort: server
      protocol: TCP
      name: server
  selector:
    app.kubernetes.io/component: neutree-core
