apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neutree.fullname" . }}-postgresql-initdb
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
data:
  000_init.sql: |
    {{- .Files.Get "init-scripts/000_init.sql" | nindent 4 }}
