apiVersion: v1
kind: Service
metadata:
  name: {{ include "neutree.fullname" . }}-postgresmeta-service
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresmeta.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: neutree-postgresmeta