apiVersion: v1
kind: Service
metadata:
  name: {{ include "neutree.fullname" . }}-postgrest-service
  labels:
    {{- include "neutree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgrest.service.type }}
  ports:
    - port: 6432
      targetPort: 6432
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: neutree-postgrest