{
 "title": "Neutree Endpoint Token Latency Embed",
 "tags": [
  "neutree",
  "endpoint",
  "token",
  "embed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": "label_values(neutree_node_ready, neutree_cluster)"
   },
   {
    "name": "Endpoint",
    "query": "label_values(neutree_node_gpu_allocation{neutree_cluster=~\"$Cluster\"}, endpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prompt tokens/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Generation tokens/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vllm:generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(sglang_gen_throughput{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total tokens/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(vllm:prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or vector(0)) + (sum(rate(vllm:generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(sglang_gen_throughput{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Token throughput trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "prompt tokens/s"
    },
    {
     "expr": "sum(rate(vllm:generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(sglang_gen_throughput{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}) or vector(0)",
     "legendFormat": "generation tokens/s"
    },
    {
     "expr": "(sum(rate(vllm:prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_prompt_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or vector(0)) + (sum(rate(vllm:generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(rate(sglang_generation_tokens_total{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum(sglang_gen_throughput{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}) or vector(0))",
     "legendFormat": "total tokens/s"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum by(le) (increase(sglang_prompt_tokens_histogram_bucket{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval])) or sum by(le) (increase(sglang_generation_tokens_histogram_bucket{neutree_cluster=~\"$Cluster\",application=~\".*$Endpoint.*\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}