// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	v1 "github.com/neutree-ai/neutree/api/v1"
	registry "github.com/neutree-ai/neutree/internal/registry"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryService is an autogenerated mock type for the RepositoryService type
type MockRepositoryService struct {
	mock.Mock
}

type MockRepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryService) EXPECT() *MockRepositoryService_Expecter {
	return &MockRepositoryService_Expecter{mock: &_m.Mock}
}

// DetectListRepositoriesCapability provides a mock function with given fields: target
func (_m *MockRepositoryService) DetectListRepositoriesCapability(target registry.RepositoryTarget) (v1.ListRepositoriesCapability, error) {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for DetectListRepositoriesCapability")
	}

	var r0 v1.ListRepositoriesCapability
	var r1 error
	if rf, ok := ret.Get(0).(func(registry.RepositoryTarget) (v1.ListRepositoriesCapability, error)); ok {
		return rf(target)
	}
	if rf, ok := ret.Get(0).(func(registry.RepositoryTarget) v1.ListRepositoriesCapability); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(v1.ListRepositoriesCapability)
	}

	if rf, ok := ret.Get(1).(func(registry.RepositoryTarget) error); ok {
		r1 = rf(target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryService_DetectListRepositoriesCapability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectListRepositoriesCapability'
type MockRepositoryService_DetectListRepositoriesCapability_Call struct {
	*mock.Call
}

// DetectListRepositoriesCapability is a helper method to define mock.On call
//   - target registry.RepositoryTarget
func (_e *MockRepositoryService_Expecter) DetectListRepositoriesCapability(target interface{}) *MockRepositoryService_DetectListRepositoriesCapability_Call {
	return &MockRepositoryService_DetectListRepositoriesCapability_Call{Call: _e.mock.On("DetectListRepositoriesCapability", target)}
}

func (_c *MockRepositoryService_DetectListRepositoriesCapability_Call) Run(run func(target registry.RepositoryTarget)) *MockRepositoryService_DetectListRepositoriesCapability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.RepositoryTarget))
	})
	return _c
}

func (_c *MockRepositoryService_DetectListRepositoriesCapability_Call) Return(_a0 v1.ListRepositoriesCapability, _a1 error) *MockRepositoryService_DetectListRepositoriesCapability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryService_DetectListRepositoriesCapability_Call) RunAndReturn(run func(registry.RepositoryTarget) (v1.ListRepositoriesCapability, error)) *MockRepositoryService_DetectListRepositoriesCapability_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepositories provides a mock function with given fields: target, hint, query
func (_m *MockRepositoryService) ListRepositories(target registry.RepositoryTarget, hint v1.ListRepositoriesCapability, query registry.RepositoryQuery) (registry.RepositoryPage, error) {
	ret := _m.Called(target, hint, query)

	if len(ret) == 0 {
		panic("no return value specified for ListRepositories")
	}

	var r0 registry.RepositoryPage
	var r1 error
	if rf, ok := ret.Get(0).(func(registry.RepositoryTarget, v1.ListRepositoriesCapability, registry.RepositoryQuery) (registry.RepositoryPage, error)); ok {
		return rf(target, hint, query)
	}
	if rf, ok := ret.Get(0).(func(registry.RepositoryTarget, v1.ListRepositoriesCapability, registry.RepositoryQuery) registry.RepositoryPage); ok {
		r0 = rf(target, hint, query)
	} else {
		r0 = ret.Get(0).(registry.RepositoryPage)
	}

	if rf, ok := ret.Get(1).(func(registry.RepositoryTarget, v1.ListRepositoriesCapability, registry.RepositoryQuery) error); ok {
		r1 = rf(target, hint, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryService_ListRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepositories'
type MockRepositoryService_ListRepositories_Call struct {
	*mock.Call
}

// ListRepositories is a helper method to define mock.On call
//   - target registry.RepositoryTarget
//   - hint v1.ListRepositoriesCapability
//   - query registry.RepositoryQuery
func (_e *MockRepositoryService_Expecter) ListRepositories(target interface{}, hint interface{}, query interface{}) *MockRepositoryService_ListRepositories_Call {
	return &MockRepositoryService_ListRepositories_Call{Call: _e.mock.On("ListRepositories", target, hint, query)}
}

func (_c *MockRepositoryService_ListRepositories_Call) Run(run func(target registry.RepositoryTarget, hint v1.ListRepositoriesCapability, query registry.RepositoryQuery)) *MockRepositoryService_ListRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.RepositoryTarget), args[1].(v1.ListRepositoriesCapability), args[2].(registry.RepositoryQuery))
	})
	return _c
}

func (_c *MockRepositoryService_ListRepositories_Call) Return(_a0 registry.RepositoryPage, _a1 error) *MockRepositoryService_ListRepositories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryService_ListRepositories_Call) RunAndReturn(run func(registry.RepositoryTarget, v1.ListRepositoriesCapability, registry.RepositoryQuery) (registry.RepositoryPage, error)) *MockRepositoryService_ListRepositories_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryService creates a new instance of MockRepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryService {
	mock := &MockRepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
