---
dir: mocks
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: mocks
with-expecter: true
packages:
  github.com/neutree-ai/neutree/pkg/storage:
    interfaces:
      Storage:
      ObjectStorage: