---
dir: mocks
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: mocks
with-expecter: true
packages:
  github.com/neutree-ai/neutree/internal/orchestrator/ray:
    interfaces:
      ClusterManager: