ARG RAY_BASE_IMAGE
ARG RAY_COMMIT
ARG VLLM_VERSION=0.11.2
ARG COMMON_WORKDIR=/app
ARG RAY_REPO
ARG RAY_BUILD_BASE_IMAGE="quay.io/pypa/manylinux2014_x86_64:2024-07-02-9ac04ee"

FROM alpine/git:v2.47.2 as ray_fetch
ARG RAY_REPO
ARG RAY_COMMIT
ARG COMMON_WORKDIR
WORKDIR ${COMMON_WORKDIR}
RUN git clone ${RAY_REPO} \
	    && cd ray \
	    && git checkout ${RAY_COMMIT}

FROM ${RAY_BUILD_BASE_IMAGE} AS build_ray
ARG COMMON_WORKDIR
ARG RAY_COMMIT
ENV BUILDKITE_COMMIT=${RAY_COMMIT}
ENV TRAVIS_COMMIT=${BUILDKITE_COMMIT}
ENV BUILD_ONE_PYTHON_ONLY=py311
ENV RAY_DISABLE_EXTRA_CPP=1
WORKDIR /ray
COPY --from=ray_fetch ${COMMON_WORKDIR}/ray /ray
RUN /ray/python/build-wheel-manylinux2014.sh

FROM ${RAY_BASE_IMAGE}

ARG VLLM_VERSION

USER ray

# Install ray (same version as cluster image)
RUN --mount=type=bind,from=build_ray,src=/ray,target=/install \
    cd /install \
    && pip install -U -r python/requirements.txt \
    && pip uninstall -y ray \
    && pip install .whl/*.whl

# Install common dependencies
RUN --mount=type=bind,src=requirements,target=requirements \
    pip install --no-cache-dir -r requirements/common.txt

# Install vLLM (specific version)
RUN pip install --no-cache-dir vllm==${VLLM_VERSION}

# Copy Python files
COPY *.py ./
COPY serve ./serve
COPY downloader ./downloader

CMD ["/bin/bash"]
