// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/neutree-ai/neutree/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterReconcile is an autogenerated mock type for the ClusterReconcile type
type MockClusterReconcile struct {
	mock.Mock
}

type MockClusterReconcile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterReconcile) EXPECT() *MockClusterReconcile_Expecter {
	return &MockClusterReconcile_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function with given fields: ctx, _a1
func (_m *MockClusterReconcile) Reconcile(ctx context.Context, _a1 *v1.Cluster) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterReconcile_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type MockClusterReconcile_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Cluster
func (_e *MockClusterReconcile_Expecter) Reconcile(ctx interface{}, _a1 interface{}) *MockClusterReconcile_Reconcile_Call {
	return &MockClusterReconcile_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, _a1)}
}

func (_c *MockClusterReconcile_Reconcile_Call) Run(run func(ctx context.Context, _a1 *v1.Cluster)) *MockClusterReconcile_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Cluster))
	})
	return _c
}

func (_c *MockClusterReconcile_Reconcile_Call) Return(_a0 error) *MockClusterReconcile_Reconcile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterReconcile_Reconcile_Call) RunAndReturn(run func(context.Context, *v1.Cluster) error) *MockClusterReconcile_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileDelete provides a mock function with given fields: ctx, _a1
func (_m *MockClusterReconcile) ReconcileDelete(ctx context.Context, _a1 *v1.Cluster) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Cluster) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterReconcile_ReconcileDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileDelete'
type MockClusterReconcile_ReconcileDelete_Call struct {
	*mock.Call
}

// ReconcileDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Cluster
func (_e *MockClusterReconcile_Expecter) ReconcileDelete(ctx interface{}, _a1 interface{}) *MockClusterReconcile_ReconcileDelete_Call {
	return &MockClusterReconcile_ReconcileDelete_Call{Call: _e.mock.On("ReconcileDelete", ctx, _a1)}
}

func (_c *MockClusterReconcile_ReconcileDelete_Call) Run(run func(ctx context.Context, _a1 *v1.Cluster)) *MockClusterReconcile_ReconcileDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Cluster))
	})
	return _c
}

func (_c *MockClusterReconcile_ReconcileDelete_Call) Return(_a0 error) *MockClusterReconcile_ReconcileDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterReconcile_ReconcileDelete_Call) RunAndReturn(run func(context.Context, *v1.Cluster) error) *MockClusterReconcile_ReconcileDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterReconcile creates a new instance of MockClusterReconcile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterReconcile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterReconcile {
	mock := &MockClusterReconcile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
