name: Daily Build

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  create_daily_tag:
    runs-on: ubuntu-latest
    name: Create Nightly Tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Create Nightly Tag
        id: create_nightly_tag
        run: |
          DATE=$(date +'%Y%m%d')
          NIGHTLY_TAG="v1.1.0-nightly-${DATE}"
          git tag "${NIGHTLY_TAG}" -m "${NIGHTLY_TAG}"
          git push origin "${NIGHTLY_TAG}"
          echo "tag=${NIGHTLY_TAG}" >> "${GITHUB_OUTPUT}"
      - name: Trigger Workflow
        uses: actions/github-script@v7
        env:
          NIGHTLY_CLUSTER_VERSION: ${{ secrets.NIGHTLY_CLUSTER_VERSION }}
        with:
          script: |
            const nightlyTag = '${{ steps.create_nightly_tag.outputs.tag }}';
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yaml',
              ref: 'main',
              inputs: {
                tag: nightlyTag,
                ui_version: nightlyTag,
                cluster_version: process.env.NIGHTLY_CLUSTER_VERSION
              },
            })
